include/Util/Conditions.h

Fixes crash near exit when using SABER.

BddCondManager: fix deallocation to use Cudd_Quit.

---

.travis.yml
CMakeLists.txt
lib/CMakeLists.txt

Script so that travis can be enabled for the repo
https://travis-ci.org/stephengroat/SVF/builds/234668158

Travis CI Scripts

---

include/MemoryModel/PAGBuilder.h
lib/MemoryModel/PAGBuilder.cpp

Revert "Fix bug for creating gep value node"

---

include/MemoryModel/PAGBuilder.h
lib/MemoryModel/PAGBuilder.cpp

get the original commit form yiyuaner

"Fix bug for creating gep value node" from yiyuaner

---

.gitignore
CMakeLists.txt

With this commit, headers will be installed inside $PREFIX/svf/ directory

install headers

---

include/Util/BasicTypes.h

Add debug-related types to BasicTypes.

---

include/MemoryModel/PAGNode.h
include/SABER/FileChecker.h
include/SABER/LeakChecker.h
include/WPA/WPAPass.h
lib/Util/SVFUtil.cpp
lib/Util/ThreadCallGraph.cpp
lib/WPA/TypeAnalysis.cpp

Fixed WPA pass so that opt can run it and eliminated a bunch of compiler warnings.

Small fixes

---

include/Util/ThreadAPI.h

Fix an incorrect function call #157

Fix an incorrect function call #157

---

lib/MemoryModel/PointerAnalysisImpl.cpp

As title, simple change for nicer output.

Order print-all-pts

---

include/WPA/FlowSensitiveTBHC.h
lib/MemoryModel/PointerAnalysis.cpp
lib/SVF-FE/DCHG.cpp
lib/Util/TypeBasedHeapCloning.cpp
lib/WPA/FlowSensitiveTBHC.cpp

All pertaining to FSTBHC and DCHG except the check in `PointerAnalysis.cpp`.

FSTBHC fixes

---

include/WPA/FlowSensitive.h
lib/WPA/FlowSensitive.cpp
lib/WPA/FlowSensitiveStat.cpp
lib/WPA/FlowSensitiveTBHC.cpp

* Added Phi and separated copy and GEP.
* I was going to add stats for FR->AR/AP->FP but it seems the times they take are just so small so it's not worth it. I made the code a little simpler though.

Add more stats to FSPTA

---

include/Graphs/ExternalPAG.h
include/Util/SVFBasicTypes.h
lib/Graphs/SVFGStat.cpp
lib/MemoryModel/PointerAnalysisImpl.cpp
lib/SVF-FE/DCHG.cpp
lib/Util/PTAStat.cpp
lib/WPA/AndersenStat.cpp

As title, a counterpart to `NodeSet`.

Add typedef for DenseSets of NodeIDs

---

CMakeLists.txt
include/DDA/DDAClient.h
include/DDA/DDAVFSolver.h
include/SVF-FE/LLVMUtil.h
include/SVF-FE/PAGBuilder.h
include/WPA/Andersen.h

Fixes a few warnings in headers.

Warning fixes

---

lib/CMakeLists.txt
lib/CUDD/CMakeLists.txt

activate with "-DBUILD_SHARED_LIBS=on"

CMake: support building of shared libraries

---

include/WPA/WPAPass.h
lib/WPA/WPAPass.cpp

This pull request makes the `WPAPass` a LLVM module pass. See #289 for details.

Make WPAPass a LLVM ModulePass

---

build.sh

build.sh: use as many cores as available for compilation

---

include/DDA/ContextDDA.h
include/DDA/FlowDDA.h
include/MemoryModel/MutablePointsToDS.h

Fixes compiler warnings introduced by #331.

Fix override warnings

---

include/MemoryModel/AbstractPointsToDS.h
include/MemoryModel/MutablePointsToDS.h
include/MemoryModel/PointerAnalysisImpl.h
include/WPA/Andersen.h

* Make exposed interface `const`
* Unexpose `getPropaPts` (unused outside the class)
* Fix a `classof` bug
* Remove cache map

Slight refactor of DiffPTData

---

lib/WPA/Andersen.cpp
lib/WPA/FlowSensitive.cpp

As discussed yesterday. Only tested on small bitcode inputs for FSPTA because #354 but tested on Andersen's.

Pull conditional checks out of loop

---

include/Graphs/PAG.h
include/Graphs/PAGNode.h
include/SVF-FE/PAGBuilder.h
include/SVF-FE/SymbolTableInfo.h
lib/Graphs/PAG.cpp
lib/MSSA/MemRegion.cpp
lib/MemoryModel/MemModel.cpp
lib/MemoryModel/PointerAnalysis.cpp
lib/SVF-FE/CHG.cpp
lib/SVF-FE/LLVMModule.cpp
lib/SVF-FE/PAGBuilder.cpp
lib/SVF-FE/SymbolTableInfo.cpp
lib/Util/PTAStat.cpp

1. Some code improvement in PAGBuilder::build
2. Fix some typos

Code improvement

---

include/WPA/VersionedFlowSensitive.h
lib/WPA/VersionedFlowSensitive.cpp

Copied from `FlowSensitive`. I think this should solve what you're after.

Add singleton VFSPTA

---

.travis.yml
CMakeLists.txt
build.sh

Moving tests from build.sh to Travis CI

Move tests to Travis CI

---

.travis.yml
build.sh
include/SVF-FE/GEPTypeBridgeIterator.h

1. fix OS version conflict
2. fix type casting error in GEPTypeBridgeIterator

Fix CI pass error

---

lib/DDA/ContextDDA.cpp

issue: #444 
PS: I'm not sure if the check on `DummyValNode` is correct

contextDDA: add check on NULL refVal in isHeapCondMemObj

---

lib/MemoryModel/PointerAnalysisImpl.cpp
lib/WPA/Andersen.cpp

1. IO handle problem on reading big file
2. Insufficient information recorded when storing the analysis result

Fix some issues on andersen analysis result recovering

---

lib/SVF-FE/CPPUtil.cpp

Disable thunk-related assertions

---

.travis.yml
build.sh

Remove generating bc files when building

Remove generate bc from build.sh

---

.github/workflows/github-action.yml
doc/doxygen.config

add github actions
change doxygen project name

add github actions

---

include/WPA/VersionedFlowSensitive.h
lib/WPA/VersionedFlowSensitive.cpp

In many instances we were doing...
```
if hasYield(l, o):
y = yield[l][o];  // or sometimes y = yieldl[o]
```
resulting in two map lookups (modulo nesting): one for `hasYield` and one to actually get the value. An alternative would be to use `find`, but it's not pleasant having all these extra one-use iterators around. This patch defines `getYield` and `getConsume` to instead do...
```
y = getYield(l, o);  // Internally, this is a map lookup.
if y != invalidVersion:
use y;
```
thus resulting in a map lookup  (wrapper on `find`) and a comparison.
`get{Yield,Consume}` also cache the first layer of lookup, i.e. `yield[l]` or `consume[l]`, allowing the user to not have to worry about this (we often would do something like `&consumel = consume[l]` then perform `consumel[o]` lookups in a loop}. …

Cache consume and yield maps in VFS

---

include/Graphs/SVFG.h
lib/Graphs/SVFG.cpp

SVFG: rename fromLLVMValue to fromValue

---

include/MemoryModel/PTAStat.h
include/SABER/SrcSnkDDA.h
lib/SABER/SrcSnkDDA.cpp
lib/SVF-FE/ICFGBuilder.cpp
lib/Util/PTAStat.cpp
tools/Example/svf-ex.cpp
tools/SABER/saber.cpp

fix circular reference
connect Global ICFG Node to entry

fix circular reference + connect Global ICFG Node to entry

---

lib/WPA/FlowSensitive.cpp
lib/WPA/VersionedFlowSensitive.cpp

As discussed, this bounds the FS call graph by that coming from Andersen's.

Bound FS call graph

---

include/Graphs/SVFG.h
include/Graphs/SVFGOPT.h
include/MSSA/MemPartition.h
include/MSSA/MemRegion.h
include/MSSA/MemSSA.h
include/MSSA/SVFGBuilder.h
include/MemoryModel/LocationSet.h
include/MemoryModel/PersistentPointsToCache.h
include/MemoryModel/PointerAnalysisImpl.h
include/Util/SVFUtil.h
lib/Graphs/SVFG.cpp
lib/Graphs/SVFGOPT.cpp
lib/MSSA/MemPartition.cpp
lib/MSSA/MemRegion.cpp
lib/MSSA/MemSSA.cpp
lib/MemoryModel/LocationSet.cpp
lib/MemoryModel/PointerAnalysisImpl.cpp
lib/Util/SVFUtil.cpp

Move some PointsTo to NodeBS

---

LICENSE.TXT
include/FastCluster/LICENSE.TXT
include/FastCluster/fastcluster.h
lib/CMakeLists.txt
lib/FastCluster/LICENSE.TXT
lib/FastCluster/fastcluster.cpp
lib/FastCluster/fastcluster_R_dm.cpp.inc
lib/FastCluster/fastcluster_dm.cpp.inc

This doesn't change any functionality, just adds third party code.

Add fastcluster

---

include/DDA/DDAVFSolver.h
include/Graphs/SVFGEdge.h
include/Graphs/SVFGNode.h
include/MTA/FSMPTA.h
include/MemoryModel/ConditionalPT.h
include/SABER/SaberSVFGBuilder.h
lib/Graphs/SVFGStat.cpp
lib/Graphs/ThreadCallGraph.cpp
lib/MTA/FSMPTA.cpp
lib/MemoryModel/PointerAnalysis.cpp
lib/SABER/SaberSVFGBuilder.cpp
lib/WPA/FlowSensitive.cpp
lib/WPA/FlowSensitiveTBHC.cpp
lib/WPA/VersionedFlowSensitive.cpp

More NodeBS/PointsTo finangling

---

lib/SVF-FE/BreakConstantExpr.cpp

This PR fixes issue #522  and is necessary to pass the autotest when compiling with LLVM 13.0 release binary

Change BreakConstantExpr to use ConstantExpr::getAsInstruction()

---

.github/workflows/github-action.yml
CMakeLists.txt
Dockerfile
build.sh
include/Graphs/GraphPrinter.h
include/MemoryModel/MutablePointsToDS.h
include/MemoryModel/PointerAnalysisImpl.h
include/Util/BasicTypes.h
lib/DDA/DDAPass.cpp
lib/MemoryModel/PointerAnalysis.cpp
lib/MemoryModel/PointerAnalysisImpl.cpp
lib/SVF-FE/Graph2Json.cpp
lib/SVF-FE/LLVMModule.cpp
lib/Util/TypeBasedHeapCloning.cpp
lib/WPA/FlowSensitive.cpp
lib/WPA/FlowSensitiveTBHC.cpp
lib/WPA/WPAPass.cpp
setup.sh

The upstream LLVM git repository has changed major version to 14. There are some breaking changes in LLVM API, and this PR fixes compilation issues against the new API.
Most of this patch is adapted from PR #520

Add support for LLVM 13 release

---

include/MemoryModel/PersistentPointsToCache.h
include/MemoryModel/PointerAnalysisImpl.h
lib/MemoryModel/PointerAnalysisImpl.cpp
lib/WPA/FlowSensitive.cpp

Fairly simple, the commits + diff should explain.

Improve statistics

---

include/Graphs/GenericGraph.h
include/MemoryModel/PersistentPointsToCache.h
include/MemoryModel/PointerAnalysisImpl.h
include/Util/SVFModule.h
lib/Graphs/PAG.cpp
lib/SVF-FE/SymbolTableInfo.cpp
lib/Util/Options.cpp

This fixes #580 and works at least for my small example. There were a few more issues and I hope I fixed them without breaking any invariants.

Fix memory leaks

---

include/SABER/PathCondAllocator.h
include/Util/Conditions.h
lib/SABER/ProgSlice.cpp
lib/Util/Conditions.cpp

As per discussed, add true/false branch information in the bug report.

Print true/false branch information

---

include/MemoryModel/LocationSet.h
include/MemoryModel/SVFStatements.h
include/MemoryModel/SymbolTableInfo.h
lib/MemoryModel/LocationSet.cpp
lib/MemoryModel/SymbolTableInfo.cpp

@mbarbar Can you help test whether we can obtain the correct offset if using GepStmt->accumulateConstantOffset().
Please also feel free to suggest better naming conventions based on our discussion.

compute accumulateConstantOffset of a GepStmt

---

lib/Util/ExtAPI.cpp

add external API

---

include/Graphs/SVFGNode.h
include/Graphs/VFGNode.h
lib/Graphs/SVFG.cpp
lib/Graphs/VFG.cpp

add getDefSVFVars for VFGNode

---

include/Util/BasicTypes.h
lib/Graphs/IRGraph.cpp

- Add selectStmt to IRGraph
- Add getArg to SVFFucntion

selectStmt and getArg

---

lib/Graphs/SVFG.cpp

SVFG: fix typo (phi -> mphi)

---

include/SABER/PathCondAllocator.h
include/Util/Conditions.h
include/Util/Options.h
lib/SABER/PathCondAllocator.cpp
lib/Util/Conditions.cpp
lib/Util/Options.cpp

now we can use bdd or z3 condition as designated by the cmd option.

decoupling bdd and z3 condition (manager)

---

build.sh

Extends #654 to build from source on M1 machines.

Build LLVM, Z3 on M1 from scratch

---

lib/Util/ExeState.cpp

fix judging equal

---

include/Util/ExeState.h
lib/Util/ExeState.cpp

refactor equal and lessthan

---

include/Graphs/GraphPrinter.h
include/Graphs/SVFG.h
include/MSSA/MSSAMuChi.h
include/SABER/SaberCheckerAPI.h
include/SVF-FE/BasicTypes.h
include/SVF-FE/LLVMModule.h
include/Util/BasicTypes.h
include/Util/ExtAPI.h
include/Util/SVFBasicTypes.h
include/Util/ThreadAPI.h
lib/Graphs/SVFG.cpp
lib/MemoryModel/PointerAnalysisImpl.cpp
lib/SABER/SaberSVFGBuilder.cpp
lib/SVF-FE/Graph2Json.cpp
lib/Util/ThreadAPI.cpp

Most of what we discussed, more to come.

Remove some LLVM deps

---

include/CFL/CFGNormalizer.h
include/CFL/CFLAlias.h
include/CFL/CFLChecker.h
include/CFL/CFLGramGraphChecker.h
include/CFL/CFLGrammar.h
include/CFL/CFLGrammar.txt
include/CFL/CFLGraphBuilder.h
include/CFL/GrammarBuilder.h
include/Graphs/CFLGraph.h
include/Graphs/GenericGraph.h
lib/CFL/CFGNormalizer.cpp
lib/CFL/CFLGrammar.cpp
lib/CFL/CFLGraphBuilder.cpp
lib/CFL/CFLSolver.cpp
lib/CFL/GrammarBuilder.cpp
lib/Graphs/CFLGraph.cpp

Support Attribute Grammar
Support EBNF Transformation
Support Grammar Print out
Decoupling with additional builder

CFL Development Pull Request

---

include/MTA/MHP.h
include/MemoryModel/SVFVariables.h
include/MemoryModel/SymbolTableInfo.h
include/SVF-FE/BasicTypes.h
include/Util/BasicTypes.h
lib/MTA/TCT.cpp
lib/MemoryModel/LocationSet.cpp
lib/MemoryModel/SVFVariables.cpp
lib/MemoryModel/SymbolTableInfo.cpp
lib/Util/ExeState.cpp

refactor llvm::constantData

---

include/SVF-FE/BasicTypes.h
include/Util/BasicTypes.h
lib/WPA/FlowSensitiveTBHC.cpp
lib/WPA/TypeBasedHeapCloning.cpp

Move some LLVM to SVF-FE

---

include/DDA/ContextDDA.h
include/DDA/FlowDDA.h
include/Graphs/ICFG.h
include/MTA/TCT.h
include/MemoryModel/SVFLoop.h
include/SVF-FE/LLVMLoopAnalysis.h
include/Util/Options.h
lib/DDA/ContextDDA.cpp
lib/DDA/FlowDDA.cpp
lib/Graphs/ICFG.cpp
lib/SVF-FE/LLVMLoopAnalysis.cpp
lib/SVF-FE/SVFIRBuilder.cpp
lib/Util/Options.cpp
tools/WPA/wpa.cpp

- add SVFLoop to MemoryModel/
- add LLVMLoopAnalysis to SVF-FE/

addSVFLoop and LLVMLoopAnalysis

---

include/Util/SymState.h

add symstate

---

lib/Util/ExtAPI.cpp

read external API case-sensitively

read external API case-sensitively

---

include/Util/ExtAPI.json

support string move constructor, c++11

---

include/Util/DPItem.h

add move constructor/operator= for DPItem

add move constructor/operator= for DPItem

---

include/Util/SVFUtil.h

wrap std::move

---

include/Util/SVFUtil.h

pass rvalue in move

---

LICENSE.TXT
include/MemoryModel/PointsTo.h
include/Util/SVFBasicTypes.h
include/Util/SparseBitVector.h
lib/MemoryModel/PointsTo.cpp
lib/Util/CoreBitVector.cpp

As title. Draft till tests pass.
There was a need to bring some bit-fiddling functions from LLVM over too.

Bring SparseBitVector into tree

---

include/Util/Z3Expr.h
lib/SABER/SaberCondAllocator.cpp
lib/Util/ExeState.cpp
lib/Util/Z3Expr.cpp

releasing solver after releasing context can cause a double-free bug

fix release solver after release context bug

---

lib/MemoryModel/LocationSet.cpp

getElementNum for function type

getElementNum for function type

---

lib/WPA/VersionedFlowSensitive.cpp

This improves the performance of meld labeling, namely for the printf BC, but in general too.
Problems with printf:
* There are a lot of objects compared to what the BC is actually doing (see low avg top-level points-to set size vs. number of objects). There is a loop performing `getPts` per Store node per object.
* The SVFG grew and there is a loop iterating number-of-nodes-in-svfg times _per_ object.
* After SVF-2.4, we introduced an overhaul of meld labeling that is generally better but for the reasons mentioned above, it is not better for printf. With printf's small points-to sets (but large SVFG, many objects), the extremely naive labeling of 2.4 worked better.
Stats:
SVF-2.4:
```
OLD 1 THREAD
=== printf ===
AvgTopLvlPtsSize    11.4371
meldLabelingTime    1.421
TotalTime …
```

Improve meld labeling performance

---

include/DDA/DDAPass.h
include/SVF-FE/BasicTypes.h
include/SVF-FE/CHGBuilder.h
include/SVF-FE/DCHG.h
include/SVF-FE/LLVMModule.h
include/Util/BasicTypes.h
include/Util/SVFUtil.h
include/WPA/WPAPass.h
lib/DDA/DDAPass.cpp
lib/SVF-FE/DCHG.cpp
lib/WPA/WPAPass.cpp

Refactor: llvm::Module to SVF::SVFModule

Llvm module

---

include/Graphs/ICFGStat.h
include/Util/PTAStat.h
include/Util/SVFStat.h
include/WPA/AndersenPWC.h
lib/DDA/DDAPass.cpp
lib/DDA/DDAStat.cpp
lib/Graphs/SVFGReadWrite.cpp
lib/Graphs/SVFGStat.cpp
lib/SVF-FE/CHGBuilder.cpp
lib/Util/PTAStat.cpp
lib/Util/SVFStat.cpp
lib/WPA/Andersen.cpp
lib/WPA/AndersenSCD.cpp
lib/WPA/AndersenSFR.cpp
lib/WPA/AndersenStat.cpp
lib/WPA/AndersenWaveDiff.cpp

add SVF Stat

---

include/CFL/CFLGraphBuilder.h
include/CFL/PEGGrammar.txt
lib/CFL/CFLGraphBuilder.cpp

backwards search gep src to connect vgep dst before solving CFL.

VGep Backwards handling

---

include/Util/WorkList.h

add set for worklist

---

include/CFL/CFLGrammar.h
include/CFL/CFLGrammar.txt
include/CFL/CFLStat.h
include/Graphs/CFLGraph.h
lib/CFL/CFGNormalizer.cpp
lib/CFL/CFLGrammar.cpp
lib/CFL/CFLStat.cpp

Rewrite PAG Grammar in EBNF form

---

include/Graphs/ConsGNode.h
include/Graphs/GenericGraph.h
include/Graphs/ICFG.h
include/Graphs/SVFGOPT.h
include/Graphs/VFG.h
include/MSSA/MemSSA.h
include/MemoryModel/PersistentPointsToDS.h
include/MemoryModel/SVFIR.h
include/SABER/SaberCondAllocator.h
include/SVF-FE/IRAnnotator.h
include/Util/SparseBitVector.h
lib/DDA/ContextDDA.cpp
lib/Graphs/ConsG.cpp
lib/Graphs/ICFG.cpp
lib/Graphs/VFG.cpp
lib/MSSA/MemRegion.cpp
lib/MTA/TCT.cpp
lib/MemoryModel/PointerAnalysisImpl.cpp
lib/SABER/SaberCondAllocator.cpp
lib/SVF-FE/CHGBuilder.cpp
lib/SVF-FE/SVFIRBuilder.cpp
lib/WPA/AndersenSFR.cpp
lib/WPA/TypeAnalysis.cpp

Fix warning of unused variables for assertions

Fix warning of unused defined variables caused by assertions

---

svf-llvm/lib/LLVMModule.cpp

Please refer to issue #978 for more details.

Handle empty GlobalVariable name

---

svf/lib/SABER/SrcSnkDDA.cpp

More details please see issue #980

Fix a bug in wrapper detection

---

svf/lib/SABER/SaberCondAllocator.cpp

For more details, please see issue #982.

Try to fix issue in isTestContainsNullAndTheValue

---

svf/lib/SABER/LeakChecker.cpp

 Exclude sources in functions that have summary

---

svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp

some bug in translate load.
we should start from Bottom Value and merge with Loc2Val.

fix translate Load for buf overflow cases

---

svf/include/Util/Options.h
svf/lib/SABER/SaberSVFGBuilder.cpp
svf/lib/Util/Options.cpp

Add An Option to Ignore External Functions During Global Collection

---

svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp

fix a bug in transGep, lb ub may be integer underflow/overflow

fix a bug in SVFIR2ItvExeState

---

.codecov.yml
svf-llvm/include/SVF-LLVM/DCHG.h
svf-llvm/lib/LLVMModule.cpp
svf-llvm/lib/SVFIRBuilder.cpp
svf-llvm/tools/WPA/wpa.cpp
svf/include/Graphs/CHG.h
svf/include/Graphs/GenericGraph.h
svf/include/Graphs/ICFG.h
svf/include/Graphs/ICFGEdge.h
svf/include/Graphs/ICFGNode.h
svf/include/Graphs/IRGraph.h
svf/include/MemoryModel/LocationSet.h
svf/include/MemoryModel/SVFLoop.h
svf/include/SVFIR/SVFIR.h
svf/include/SVFIR/SVFIRRW.h
svf/include/SVFIR/SVFModule.h
svf/include/SVFIR/SVFModuleRW.h
svf/include/SVFIR/SVFStatements.h
svf/include/SVFIR/SVFType.h
svf/include/SVFIR/SVFValue.h
svf/include/SVFIR/SVFVariables.h
svf/include/SVFIR/SymbolTableInfo.h
svf/include/Util/CommandLine.h
svf/include/Util/Options.h
svf/include/Util/SparseBitVector.h
svf/include/Util/ThreadAPI.h
svf/lib/Graphs/ICFG.cpp
svf/lib/SVFIR/SVFIRRW.cpp
svf/lib/SVFIR/SymbolTableInfo.cpp
svf/lib/Util/Options.cpp

- Create template class `GenericGraphWriter/Reader` so that we can reuse the code for IRGraph, ICFG, CHGraph, etc.
- JSON are generated by two formats: human readable form (more redundant but easy to read), disk saving form

SVFIR Json Writer

---

svf-llvm/lib/SVFIRBuilder.cpp

1. Add `hasInitializer` sanitizer before `getInitializer` of global variables (to avoid ```Assertion `hasInitializer() && "GV doesn't have initializer!"' failed```)
2. Refactor the handling for `funptr_ops` to abvoid if-else hell

Fix the assertion failure due to funptr_ops API

---

svf-llvm/include/SVF-LLVM/BasicTypes.h
svf-llvm/lib/LLVMModule.cpp

feat: handle ifunc

---

svf-llvm/include/SVF-LLVM/CHGBuilder.h
svf-llvm/include/SVF-LLVM/LLVMUtil.h
svf-llvm/lib/CHGBuilder.cpp
svf-llvm/lib/LLVMModule.cpp
svf-llvm/lib/LLVMUtil.cpp
svf-llvm/lib/SVFIRExtAPI.cpp
svf/include/CFL/CFLGrammar.h
svf/include/SVFIR/SVFFileSystem.h
svf/include/SVFIR/SVFType.h
svf/include/SVFIR/SVFValue.h
svf/lib/CFL/CFLGrammar.cpp
svf/lib/SVFIR/SVFFileSystem.cpp
svf/lib/SVFIR/SVFType.cpp
svf/lib/SVFIR/SVFValue.cpp
svf/lib/Util/CppUtil.cpp

- Add `SVFValue::print()`
- Add check `V->hasName()` for all `llvm::Value::getName().str()`

Add debug output functions for `SVFValue`

---

docs/doxygen.config

update doxygen path

---

svf/include/Graphs/CFBasicBlockG.h
svf/lib/Graphs/CFBasicBlockG.cpp

Add func to first BB

---

svf/lib/SVFIR/SVFValue.cpp
svf/lib/Util/CDGBuilder.cpp

fix control dependence bug: no nearest common post dominator

fix control dependence bug: no nearest common post dominator

---

CMakeLists.txt
svf-llvm/CMakeLists.txt
svf/lib/Util/CDGBuilder.cpp

fix WTO and CDG build bug

---

svf/include/WPA/AndersenPWC.h

bugfix in AndersenPWC

---

svf-llvm/lib/CppUtil.cpp

- isTemplate must have "<" and ">" after demangling
- indirect call does not have calledfunction and returns a null ptr

fix isTemplate and fix a NPD bug

---

svf-llvm/lib/LLVMModule.cpp

to fix https://github.com/SVF-tools/SVF/issues/1392

add x87 double float support, 

---

svf-llvm/include/SVF-LLVM/LLVMModule.h

https://github.com/SVF-tools/SVF/issues/1483
This patch is not widely tested, and we need to think more about how to fix the root causes

Fix issue of global representation

---

svf-llvm/lib/ICFGBuilder.cpp
svf-llvm/lib/SVFIRBuilder.cpp

fix issue 1493

---

svf-llvm/include/SVF-LLVM/CppUtil.h
svf-llvm/lib/CppUtil.cpp

fix obj type inference for c++ indirect call in constructors

---

svf/lib/Graphs/ConsG.cpp

fix using getvalue when dumping constraintgraph

---

svf-llvm/lib/LLVMModule.cpp
svf/include/SVFIR/SVFType.h

add isVarArg function type

---

svf-llvm/lib/LLVMModule.cpp
svf/include/SVFIR/SVFType.h
svf/lib/SVFIR/SVFType.cpp

more precise struct type modeling

---

svf-llvm/include/SVF-LLVM/SVFIRBuilder.h
svf/include/AE/Core/NumericValue.h
svf/include/AE/Svfexe/AEDetector.h
svf/include/AE/Svfexe/AbstractInterpretation.h
svf/include/WPA/WPAStat.h
svf/lib/AE/Svfexe/AbsExtAPI.cpp
svf/lib/AE/Svfexe/AbstractInterpretation.cpp
svf/lib/WPA/FlowSensitiveStat.cpp

1) add abort() after assert()
2) rename IN/OUT to IN_SET/OUT_SET, beacuse it has conflict with windows internal enum

fix some coding minor bugs
