.travis.yml, build.sh, include/MemoryModel/PointsToDFDS.h, include/Util/DataFlowUtil.h, include/Util/GraphUtil.h, lib/MSSA/MemSSA.cpp, lib/MemoryModel/PAGBuilder.cpp, lib/MemoryModel/PointerAnalysis.cpp, lib/Util/AnalysisUtil.cpp, lib/Util/DataFlowUtil.cpp, tests/runtest.sh
Relevant LLVM changes for updating to v6.0.0 from v4.0.0:
- The `IsPostDominators` member of `llvm::DominanceFrontierBase` has become a template parameter (https://reviews.llvm.org/D35315).
- The method `llvm::Function::getArgumentList` has been dropped in favour of `llvm::Function::arg_begin`, `llvm::Function::arg_end` and `llvm::Function::args` (https://reviews.llvm.org/rL298010).
- `tool_output_file` has been renamed `ToolOutputFile`.
- `FindAllocaDbgDeclare` has been replaced with `FindDbgAddrUses`, which returns a list of zero or one `llvm.dbg.declare` intrinsics plus zero or more `llvm.dbg.addr` intrinsics (upcast as `DbgInfoIntrinsic` objects) (https://reviews.llvm.org/D37768).
I've run the test script for the `mem_leak` directory and it all looks fine – could you advise any …
=> Update for LLVM 6.0.0

lib/MemoryModel/CHA.cpp, lib/Util/CPPUtil.cpp
An error occurs due to the Argument number is changed in LLVM-6.0. 
```
cs.paramHasAttr(0, ...) 
```
"0" is the first argument now.
Previously, in LLVM-4.0, "1" is the first argument.
This needs to be confirmed if someone knows.
=> Fix C++ Analysis Error due to LLVM-6.0 changes of Attribute argument No.

lib/Util/AnalysisUtil.cpp
The loop is spurious, we use `getSubProgram` directly from the `Function` ptr `F` to get the `DISubprogram`. The loop makes the same information appended multiple times making it unreadable.
=> Fixing fetching getSourceLocOfFunction

include/MSSA/SVFG.h
Sanity function to verify that nodes of an Intraedge always refer to the same function.
=> Adding Intraedge sanity (Part 1)

lib/MSSA/SVFG.cpp
Sanity function to verify that nodes of an Intraedge always refer to the same function.
=> Adding Intraedge sanity (Part 2)

include/MemoryModel/PointsToDFDS.h
revPts fails to get points-to information of TLV pointers corresponding to `load` instructions. This is because we fail to update the revPoints while updating points-to information of TLV pointers when a flow-sensitive analysis is used.
Here, we should use PTData to update the points-to information so that revPts to get updates correctly and furthermore, for TLV pointers points-to information is maintained in a flow-insensitive manner.
=> Fix revPts to of TLV pointers of `load` instruction.

include/Util/PTACallGraph.h, lib/CMakeLists.txt
Sometimes we need `callinstToCallGraphEdgesMap` information to get calling relations between callers and callees; therefore it may be worthy to expose this analysis result.
=> expose getCallInstToCallGraphEdgesMap for analysis

tools/SABER/CMakeLists.txt, tools/WPA/CMakeLists.txt
This PR adds some missing dependencies to `wpa` and `saber`
The problem occurs when building SVF with llvm that is built as a shared library (`-DBUILD_SHARED_LIBS=ON`), with this error message:
``` Linking CXX executable ../../bin/saber
/usr/bin/ld: ../../lib/libLLVMSvf.a(MemModel.cpp.o): undefined reference to symbol '_ZTVN4llvm22UnifyFunc
tionExitNodesE'
/src/llvm_build/lib/libLLVMTransformUtils.so.7: error adding symbols: DSO missing from command line
```
This change fixes the issue for me.
=> Add missing dependant library

lib/MemoryModel/PointerAnalysis.cpp
Previously, a fencepost error; one extra call can be resolved because it would stop when the limit is exceeded, not when it is reached.
E.g. if the limit is 0, the check would pass since !(0 > 0), which allows an indirect call to be resolved before the check begins to fail (since 1 > 0).
=> Stop indirect call resolution when limit is hit

include/Util/AnalysisUtil.h, include/Util/PTACallGraph.h, lib/MemoryModel/PointerAnalysis.cpp, lib/Util/PTACallGraph.cpp
As suggested by https://github.com/nix7965 in https://github.com/SVF-tools/SVF/issues/133
=> Corrected Method Spelling (vefityCallGraph -> verifyCallGraph)

include/Util/BasicTypes.h, lib/Util/SVFModule.cpp
`FunctionCallee` was only introduced in LLVM 9.
=> Maintain backwards compatibility

lib/WPA/WPAPass.cpp
WPAPass is able to run different pointer analysis on the bitcode but no default pointer analysis is used. This leads to the segmentation fault mention in issue #156 when querying the alias result.
In order to fix this issue, it would be safe to check if any pointer analysis is chosen before doing any further work.
This commit adds an assertion to make sure that lacking pointer analysis is not allowed. It runs `wpa` as a command-line tool or invokes `WPAPass` through a shared library. In both cases, the program will abort if no pointer analysis is specified.
=> Add no Pointer Analysis is specified assertion

include/MSSA/MemRegion.h, lib/MSSA/MemRegion.cpp
As raised in [issue 176](https://github.com/SVF-tools/SVF/issues/176). An early stage of inclusion of mod to ref in [MRGenerator::handleCallsiteModRef](https://github.com/SVF-tools/SVF/blob/master/lib/MSSA/MemRegion.cpp#L520) limits the accuracy of mod-ref analysis and makes two intermediate maps `csToRefsMap` and `csToModsMap` unuseable. Since `funToPointsToMap`, `callsiteToRefPointsToMap` and `callsiteToModPointsToMap` are the three maps that contain def-use information of memory objects and get propagated to generate the correct MSSA, a delay of inclusion of mod to ref to a later stage in [MRGenerator::collectModRefForCall()](https://github.com/SVF-tools/SVF/blob/master/lib/MSSA/MemRegion.cpp#L219) can both preserve the useful information of mod-ref analysis and maintain the …
=> delay inclusion of mod to ref to preserve useful mod-ref analysis result

include/MSSA/MemRegion.h, include/Util/BasicTypes.h, include/WPA/WPAPass.h, lib/MSSA/MemRegion.cpp, lib/WPA/WPAPass.cpp
As in pr #177, SVF now naturally support interprocedural mod-ref queries by leveraging two maps `csToRefsMap` and `csToModsMap`. This commit adds three types of mod-ref query APIs to SVF.
* mod-ref query of whether a callInst instruction can mod or ref any memory location
* mod-ref query of whether a callInst instruction can mod or ref a specific memory location
* mod-ref info between two callInst instructions, which is in line with [LLVM getModRefInfo between two calls](https://llvm.org/docs/AliasAnalysis.html#the-getmodrefinfo-methods)
In order to make queries to those two maps above, a `std::vector<SVFG*> svfgVector` is added in `class WPA` to store all the svfg constructed based on Andersen's Pointer Analysis. BitVector stores the union of all query results. The query result rule is …
=> add getModRefInfo APIs support for SVF

CMakeLists.txt
This enables usage of
```
cmake ... -D LLVM_DIR=...
```
I need this for a [meson subproject](https://mesonbuild.com/CMake-module.html). Meson supports to specify arbitrary cmake argument for the actual call of cmake but does not allow to specify environment variables.
=> cmake: allow LLVM_DIR configuring with cmake variable

lib/MSSA/MemRegion.cpp
SVF is field-sensitive when treating with class/struct objects. This causes the current getModRefInfo APIs to return NoModRef if a callisite modified/referred all fields except the base field of an object, as raised in issue #188.
The solution is to expand the mod/ref PointsTo set of callsite or the base pointer to include all fields of an object if the PointsTo set contains the base pointer.
Example
```C++
struct S {
int v1;
int v2;
int v3;
};
void setV1(S *s, int v) {
s->v1 = v;
}
void setV2(S *s, int v) {
s->v2 = v;
}
void setV3(S *s, int v) {
s->v3 = v;
}
int main(int argc, char **argv) {
S *s = (S *)malloc(sizeof(S));
s->v1 = argc;
setV1(s, argc);
setV2(s, argc);
setV3(s, argc);
return 0;
}
```
The mod-ref result between pointer `s` and callsite `setV2(s, argc)` or `setV3(s, argc)` …
=> Refine getModRefInfo APIs to accomodate with field-sensitivity of SVF

include/SVF-FE/LLVMModule.h, lib/SVF-FE/LLVMModule.cpp
WPAPass is no longer a module pass, which provides the flexibility to create a WPAPass object inside any LLVM pass and it would be helpful to generate an SVFModule through an LLVM Module.
=> Add the ability to construct an SVFModule through an LLVM Module

include/MSSA/MemRegion.h, lib/MSSA/MemRegion.cpp
Though SVF handles external functions' def-use behavior by defining a customized `extf_t`, it misses to include the results into the mod-ref analysis other than `HeapAllocExtCall`.
The reason is that in
https://github.com/SVF-tools/SVF/blob/f7b3d0e3b51b25e3894d5645a0f5172284645f29/lib/MSSA/MemRegion.cpp#L510
the `getModSideEffectOfFunction(callee)` and `getRefSideEffectOfFunction(callee)` returns nothing for callee functions who don't have definitions. To set it's mod ref sets, we have to retrieve it from the PAG edges constructed from
https://github.com/SVF-tools/SVF/blob/f7b3d0e3b51b25e3894d5645a0f5172284645f29/lib/SVF-FE/PAGBuilder.cpp#L760
An example like below
```C
int main(int argc, char **argv) {
char* s1 = (char *)malloc(sizeof(argc));    // src
char* s2 = (char …
```
=> Set mod ref sets for external callsite

lib/SVF-FE/LLVMModule.cpp
A simple fix to pass the assertion
https://github.com/SVF-tools/SVF/blob/f7b3d0e3b51b25e3894d5645a0f5172284645f29/include/Util/SVFModule.h#L134
=> Set moduleIdentifier of svfModule built from LLVM Module

lib/MSSA/MemRegion.cpp
Thanks for adding these APIs, which are really helpful. I don't consider writes (mod) to a memory location should be added to the ref set so I'm removing it.
=> Refine getRefInfoForCall()

include/Graphs/PTACallGraph.h, lib/Graphs/PTACallGraph.cpp
A generic reachability check between SVFFunctions is useful for my project and I assume it's worth adding to the public API for PTACallGraph and PTACallGraphNode.
=> Add reachability check between SVFFunctions through PTACallGraph

lib/SVF-FE/CHA.cpp
https://github.com/SVF-tools/SVF/blob/e3d5175d50ee9219a607685b39d0b86014329dd8/lib/SVF-FE/CHA.cpp#L136
never gets called since an LLVM Function is passed instead of an SVFFunction, but I assume an SVFFunction is expected.
=> Call buildCHGNodes with SVFFunction as parameter

include/SVF-FE/DataFlowUtil.h
I'm not sure what caused this exception to occur in some cases, but it always occurs during the cleanup of SVF for me now. I think it's related to the nodes in the SVFG that I consider "sources" during a source-sink analysis. I haven't dug that deep into it but this is a fix regardless.
=> Runtime exception on clean up

include/Graphs/ICFGStat.h, include/MemoryModel/PointerAnalysisImpl.h, lib/MemoryModel/PointerAnalysisImpl.cpp, lib/Util/PTAStat.cpp, lib/WPA/Andersen.cpp
Since two streams are used (`std::cout` and `llvm::outs()`) sometimes things get printed on top of each other, which makes things a bit hard to read.
A more robust solution would probably be to remove `std::cout` or `llvm::outs()` but I'm not sure it's quite as simple.
* `std::cout` has features that `llvm::outs()` doesn't which are used by SVF. This is to the best of my knowledge but I couldn't find an equivalent to `set_width` after taking a quick look, for example.
* `llvm::outs()` is built to be faster.
=> Flush some streams.

lib/Graphs/SVFGOPT.cpp
SVFG optimisation was producing different SVFGs for different runs.
My take on the reason:
`handleIntraValueFlow` solves the worklist in different orders because, despite having an underlying *ordered* data structure, it used pointers as keys (no guarantee of what is allocated where)\* where order will obviously differ. In callee `bypassMSSPHINode`, (meaningless) self-loops are introduced which change what optimisations can be performed (we check for empty in/out edges and self-loop = incoming and outgoing edge). So, because of the differing order of the worklist and introduction of self-loops "blocking" optimisations, inconsistent results are produced each run.
From my testing, I've seen a case where better results are produced than any of the inconsistent runs because a final self-loop …
=> Make SVFG optimisation consistent

include/MemoryModel/PTAStat.h, lib/DDA/ContextDDA.cpp, lib/DDA/FlowDDA.cpp, lib/MSSA/MemSSA.cpp, lib/MTA/LockAnalysis.cpp, lib/MTA/MHP.cpp, lib/Util/PTAStat.cpp, lib/WPA/FlowSensitive.cpp
`clock()` is really slow, so a lot of overhead is added when we repeatedly call `getClk` in `processLoad`, `processStore`, etc. As it is, it is good for debugging, but not for actual usage and benchmarking. This patch gives a bit of command line control of `getClk`. If `-marked-clocks-only`, only a select few `getClk` calls will succeed (those which happen rarely, usually those which represent a full analysis or similar). I'm unfamiliar with some of the analyses so I may have missed some `getClk`s that should be marked.
Example of the effect, not tested on huge programs:
```
$ ./bin/wpa -fspta mruby.bc | ag totaltime
TotalTime           15.617
TotalTime           0.931
TotalTime           30.524
$ ./bin/wpa -fspta -marked-clocks-only mruby.bc | ag totaltime
TotalTime           9.623 …
```
=> Add option to control clock a little

include/Graphs/ConsG.h, include/WPA/Andersen.h, lib/MemoryModel/PointerAnalysisImpl.cpp, lib/WPA/Andersen.cpp, lib/WPA/AndersenStat.cpp, lib/WPA/FlowSensitive.cpp
I thought some more about using `isFIObj` vs. `isFieldInsensitive` in `processLoad`, and I think `isFieldInsensitive` is more appropriate. It appears to me that it is (sound but) imprecise to use `isFIObj`. Although, yes `o` is an alias of `o.f_n`, it is only a partial alias: the two objects don't necessarily point to the same thing. When you are loading from `q` when `pt(q) = { o }`, you are after `o`'s points-to, not `o.f_n`'s, and `o`'s points-to refers to what was stored to `o` (i.e. the 0th offset into `o`).
Another issue is this does not appear to be what is done in Andersen's, so it is inconsistent. With some preliminary testing, I see that FS points-to sets are not all subsets of Andersen points-to sets. In the test cases I tried, this patch fixes it.
There is a problem I'm unsure …
=> Field-insensitivity

include/Util/SVFUtil.h, lib/Graphs/ICFG.cpp, lib/SVF-FE/ICFGBuilder.cpp, lib/SVF-FE/LLVMUtil.cpp, lib/SVF-FE/PAGBuilder.cpp
This PR contains two changes for the ICFG:
- It ignores all intrinsics now, not just calls to `llvm.dbg.` but also calls to e.g. `llvm.donothing` etc.
- It does not fail anymore, if a function is not implemented (i.e. does not have any BasicBlock).
=> Improve ICFG

include/Graphs/VFG.h
This is for #272. For my test cases, it appears that optimised vs unoptimised are now giving the same results with these changes.
The functions which propagate aparm->fparm/fret->aret slipped my mind whilst making #272, so these nodes were definitely handled by FSPTA but they were being connected a bit weird. Before, for example, some formal parameters had incoming edges from non-actual parameters, I assume for optimisation's sake.
`mruby` also runs as expected, taking 20s vs. 34s for optimised vs. unoptimised.
=> Connecting Formal/Actual Parameters/Returns

include/MemoryModel/LocationSet.h
I noticed that the two constructors `LocationSet(const LocationSet& ls)` and `LocationSet(const FieldInfo& fi)` do not set the `byteOffset`. The pull request fixes this issue.
=> Fix constructor not setting byteOffset

include/DDA/DDAPass.h, include/WPA/WPAPass.h, lib/DDA/DDAPass.cpp, lib/WPA/WPAPass.cpp
This pull request fixes the `DDAPass` to be callable with a LLVM Module directly. See #289 for more details.
=> Fix DDAPass being called with a LLVM Module

include/SVF-FE/LLVMModule.h, lib/SVF-FE/LLVMModule.cpp
It does the following:
- module references are not converted to unique_ptr anymore, thus fixing
a possible use after free
- the cxts pointer is freed, fixing a memleak
- simplify handling of for loops
- unify handling of buildSVFModule(namevector) and buildSVFModule(module)
As a side effect the SymbolTableInfo is always generated, which works
around a segfault, see #269
Fixes: #260
Workaround: #269
=> LLVMModule: fix memory handling

CMakeLists.txt, include/MSSA/MSSAMuChi.h, include/MSSA/MemRegion.h, include/MSSA/MemSSA.h, lib/MSSA/MemSSA.cpp
1. build.sh: use ninja:
This has the main advantage that ninja uses all cores per default resulting in a faster compilation on machines with more or less than 4 cores.
2. MSSA: rename VERSION to MRVERSION:
When SVF is used as a library, VERSION as class name can conflict with already defined preprocessor constants. MRVERSION tries to mitigates this. (I can also rename it to something else, if you prefer this. VERSION has the disadvantage to be a very generic name and all caps, which is often used for preprocessor constants.)
3. CMake: specify project
prevents this warning:
> CMake Warning (dev) in CMakeLists.txt:
>   No project() command is present.  The top-level CMakeLists.txt file must
>   contain a literal, direct call to the project() command.  Add a line of
>   code such as
>
> …
=> Various fixes

include/Util/ExtAPI.h, lib/SVF-FE/PAGBuilder.cpp, lib/Util/ExtAPI.cpp
Hi there,
I noticed that SVF does not properly represent calls to memset in it's SVFG (i.e., memset does not appear, in contrast to memcpy or memmove).
This fix introduces a new `ExtAPI` type for memset, for which the `PAGBuilder` inserts Load/Store/Copy edges at the right places. For the Load/Store edges, I used `addComplexConsForExt()` to mimic the behavior of `memcpy` and `memmove`.
=> Fix handling of calls to memset

include/Graphs/PAG.h, include/Graphs/PAGEdge.h, include/Graphs/VFG.h, include/Graphs/VFGNode.h, include/SVF-FE/LLVMUtil.h, include/SVF-FE/PAGBuilder.h, include/Util/BasicTypes.h, lib/Graphs/ExternalPAG.cpp, lib/Graphs/PAG.cpp, lib/Graphs/SVFG.cpp, lib/Graphs/VFG.cpp, lib/MemoryModel/PAGBuilderFromFile.cpp, lib/SVF-FE/BreakConstantExpr.cpp, lib/SVF-FE/Graph2Json.cpp, lib/SVF-FE/PAGBuilder.cpp, lib/SVF-FE/SymbolTableInfo.cpp, lib/WPA/FlowSensitive.cpp
Hi there,
while trying to analyze larger projects, including the SPEC CPU 2017 suite, we realized that some WPA analyses failed because SVF does not handle the `fneg` LLVM instruction or, more generally, does not handle unary operations at all, in contrast to binary operations. `fneg` is currently the only unary operation in LLVM, but the category might be extended in the future.
This patch adds support for unary operations to SVF. The support is implemented analogous to binary ops, in PAG, VFG, SVFG, etc. We tested the patch with our previously failing analyses on the SPEC CPU suite, which are now successfully running through.
The failing behavior we observed without this patch seems quite similar to #306 (and hence also #296), so this patch might also fix those.
=> Introduce handling of unary operations

include/MemoryModel/AbstractPointsToDS.h, include/MemoryModel/MutablePointsToDS.h, include/MemoryModel/PointerAnalysis.h, include/MemoryModel/PointerAnalysisImpl.h, lib/WPA/Andersen.cpp
Reverse points-to sets need to account for the fact that we separated key and datum. A reverse set is saying... given this **Datum**, these are **Keys** (i.e. a set of Keys, not a Data), that contain that datum in their associated **Data**. Thus it is `Map<Datum, KeySet>`. I used `Set` for the `KeySet` and suprisingly for large Andersen runs... it is faster.
For example, on my machine, (avg. TL PTS size in parentheses),
```
lynx: 74s to 57s (150.492)
bash: 29s to 20s (239.593)
astyle: 24.7s to 19.4s (211.37)
mruby: 6.466s to 6.614s (20.2511)
```
Overall, perhaps `SparseBitVector` can be reconsidered to `unordered_set` or even a plain `BitVector`*. Memory usage is obviously also an important factor to consider, though, and I didn't test that.
\* The BCs I've worked on have always had less …
=> Addendum to PTData refactor

include/Graphs/PAG.h, include/SVF-FE/SymbolTableInfo.h, include/Util/NodeIDAllocator.h, lib/Graphs/PAG.cpp, lib/SVF-FE/PAGBuilder.cpp, lib/SVF-FE/SymbolTableInfo.cpp, lib/Util/NodeIDAllocator.cpp, lib/Util/TypeBasedHeapCloning.cpp
This PR introduces dense node ID allocation, keeping the old allocation as an option.
Dense allocation:
Allocates all objects in a cluster, and all values in a cluster. This makes points-to sets more compact. This is the extent of the heuristic, however you should see good memory and time improvements, even in Andersen's.
Debug allocation:
The old allocation: objects and values are interleaved and GEPs use the multiplier.
New option is `-node-alloc-strat` and takes either `debug` or `dense` and defaults to `dense`. Node ID allocation is separated from the symbol table and used in multiple places.
=> Introduce dense node ID allocation

include/MemoryModel/PointerAnalysisImpl.h, lib/Graphs/PAG.cpp
GCC 9.3 is complaining about reaching the end of a non-void function.
=> Fix compiler warnings

lib/SVF-FE/SymbolTableInfo.cpp
`p1` and `p2` are not freed after being allocated.
This patch fixes the memory leak issue using unique_ptr.
=> Fix a memory leak bug

include/Graphs/ICFG.h
In ICFG's parent class GenericGraph, destroy() has been called once. In child's virtual destructor, we don't need to call it again since parent destructor will do that.
=> Removed redundant destroy()

lib/WPA/Andersen.cpp, lib/WPA/Steensgaard.cpp
I did a bit of profiling of the normalisation code. Since I can't run any huge benchmarks, I didn't see any difference not-within-a-margin-of-error when following a `processGepPts` style. It might be fine as is. However, it wasn't being run because the wrong parent's finalize was being called.
I've also initialised `steens`.
=> Small fixes

include/Util/NodeIDAllocator.h, lib/Util/NodeIDAllocator.cpp
This adds a new node allocation strategy, `seq`, which just allocates _everything_ sequentially, so like the `debug` strategy but allocates GEPs sequentially too.
I also moved the option code to `clEnum`.
=> Add new node allocation strategy

include/MemoryModel/PTAStat.h, include/Util/Options.h, lib/SVF-FE/SymbolTableInfo.cpp, lib/Util/NodeIDAllocator.cpp, lib/Util/Options.cpp, lib/Util/PTAStat.cpp
The Options class gathers all command line options (or at least, aims to). For example, option `X` would be accessed as `Options::X` after including `Util/Options.h`.
Why not singleton? Command line options are set once for the entire execution, it makes no sense to change these (unless we might want to internally mess with an option depending on other options, perhaps?).
**Rationale**
I wanted to add an option used in many files. It is possible to declare an `llvm::cl::opt` as `extern` in some header, then initialise it in some `.cpp`, but I thought this would be cleaner as it puts all options in one place rather than interspersed across files and allows everyone to view *any* options from one place.
**Status**
I haven't moved every option to `Options` as the testing effort would be too …
=> Make options global

include/WPA/Andersen.h, include/WPA/WPASolver.h, lib/WPA/Andersen.cpp, lib/WPA/FlowSensitive.cpp
Move the body of `solve()` in WPASolver.h to `Andersen.cpp` and `FlowSensitive.cpp` to simplify the code.
=> simplify solve() in Andersen and FlowSensitive analysis

include/MemoryModel/AbstractPointsToDS.h, include/MemoryModel/MutablePointsToDS.h, include/MemoryModel/PointerAnalysis.h, include/MemoryModel/PointerAnalysisImpl.h, include/WPA/VersionedFlowSensitive.h, lib/MemoryModel/PointerAnalysisImpl.cpp, lib/WPA/Andersen.cpp
As discussed, the reverse set data structure is now controllable.
I also disabled the reverse set when the analysis is field-insensitive. Steensgaard is always field-insensitive of course, so it's never enabled.
=> Add KeySet template parameter

.gitignore, include/SVF-FE/SymbolTableInfo.h, include/Util/Options.h, lib/SVF-FE/SymbolTableInfo.cpp, lib/Util/Options.cpp
It is helpful to be able to correlate the SymID numbers in the symbol table with the LLVM IR. This pull request adds a
--print-symbol-table
option which will print the symbol table after it has been created.
This version uses outs() instead of dbgs(), and uses Value:print instead
of Value::dump [which only exists in debug builds].
=> Add --print-symbol-table option

include/Util/BasicTypes.h, lib/Util/SVFUtil.cpp
This pull request adds a couple of methods that make use of the LLVM ViewGraph facility whereby graphs can be displayed dynamically during a debugging session. These particular methods will dump the function control flow graph corresponding to an SVFFunction, either with the instructions (viewCFG), or without the instructions (viewCFGOnly).
=> Add SVFFunction::viewCFG* methods

lib/Graphs/PAG.cpp
The offset of `newLS` can be 0, which is the base object (when `Options::FirstFieldEqBase`). This appears to be the source of rare non-subsetness of VFS (and probably FS), as we discussed earlier, since it would try to create a GEP object from the offset of `newLS`.
=> Move base check after modulus offset

include/Graphs/ICFG.h, include/Graphs/ICFGNode.h, lib/Graphs/ICFG.cpp
The changes are for the following:
1. Probably most importantly, when the dot graph of the ICFG
is produced, it was not showing the LLVM instruction for the
IntraBlockNodes if there were no PAG edges, but now it does.
2. Added a dump method for ICFGNodes which just prints the
toString() contents to the console.
3. Added a ICFG::view() method that will pop up a dot dump of the
ICFG using the viewer selected by xdg-open for .dot files.
=> Improve Interprocedural Control-Flow Graph (ICFG) debugging experience

lib/Graphs/PAG.cpp
Typo from the previous PR. Confirmed to now work as expected.
=> Use newLS when checking first-field

include/Graphs/PAG.h, include/Graphs/PAGNode.h, include/Util/Options.h, lib/Graphs/ConsG.cpp, lib/Graphs/OfflineConsG.cpp, lib/Graphs/PAG.cpp, lib/Graphs/PTACallGraph.cpp, lib/SVF-FE/CHG.cpp, lib/Util/Options.cpp
1. In the .dot dump of the PAG, and some other .dot dumps, change the
circle shapes to something different as the circles get really high
when the contents is wide. In particular made the following changes
circle         -> box
Mcircle        -> house
doublecircle   -> invhouse
2. Add a PAGNode::dump() method that will write
the value of PAGNode::toString() to outs().
3. Added PAG::view() method callable from within the
debugger that will pop up the formatted .dot dump,
provided the user configures xdg-open to display
.dot files.
=> Improve Program Assignment Graph (PAG) Debugging experience

include/Graphs/ConsG.h, include/SVF-FE/CHG.h, include/Util/Options.h, lib/Graphs/ConsG.cpp, lib/Graphs/PAG.cpp, lib/SVF-FE/CHG.cpp, lib/Util/Options.cpp
1. Added ConstraintGraph::view() which can be called from
the debugger to view the constraint graph.
2. Added option, -brief-constraint-graph (default true), to
control whether instructions are included in the dump of
the constraint graph nodes (if brief is false). Previously
the brief flag could only be manipulated by editing the
source code and rebuilding.
3. In the non-brief display, use value2String so that
if the value is a function, only the name is given rather
than dumping all of the instructions in the function.
4. In the non-brief display, provide the node Id in any
case, as it takes only a few characters and is likely
to be useful.
5. Correct NormalGepPE::toString(). Due to a presumed
cut and paste error, it was claiming to be a VariantGepPE.
=> Improve debugging of Constraint Graph

include/MemoryModel/LocationSet.h, include/Util/BasicTypes.h, include/Util/DPItem.h, include/Util/SVFBasicTypes.h
Overloading std::hash for the usage of std::pair (or more generally
another STL class) can conflict when used with other libraries that
do the same.
This commit workarounds this with a special class that fallbacks to
std::hash for all classes except std::pair and uses a special
implementation otherwise.
Since I have used `if constexpr`, this commit raises the C++ standard to C++17.
`if constexpr` is not needed (technically) and can be workarounded with
standard template metaprogramming. However, I find it more readable as is.
In my case the overloading of `std::hash<std::pair>` conflicts with [graph-tool](https://git.skewed.de/count0/graph-tool/-/blob/master/src/graph/graph_util.hh#L451)
but of course, this is only an example.
=> Replace std::hash<std::pair> with SVF::svf_hash

include/Graphs/PTACallGraph.h, include/Graphs/VFG.h, lib/Graphs/PTACallGraph.cpp, lib/Graphs/VFG.cpp, lib/MSSA/MemSSA.cpp, lib/MSSA/SVFGBuilder.cpp
1. Added PTACallGraph::view(), callable from debugger,
to display the call graph while debugging.
2. Added VFG::view(), callable from debugger,
to display the [sparse] value flow graph while debugging.
3. Use value2String in a few places to get the special
treatment for functions that it gives (instead of dumping the
IR for the whole function).
4. There were missing cases when dumping a sparse value flow
graph, resulting in assertion violations. I added code to
cover the misssing cases. You may want to check that
the colors and styles I selected are what you want.
5. I modified dumpMSSA() so it unconditionally dumps the
memory SSA without checking for Options::DumpMSSA.
In the sole place where it had been called I put the
Options::DumpMSSA check. This will allow dumpMSSA() to
be called …
=> Improve debugging of call graph and value flow graph

include/MSSA/MemRegion.h, include/Util/SVFUtil.h, lib/Graphs/SVFG.cpp, lib/Graphs/VFG.cpp, lib/Util/SVFUtil.cpp
1. Some of the DOT graph writers were using "style=double" which the dot program says is invalid. I replaced this with "penwidth=2" which I believe gives the desired effect.
2. I added an "isNodeHidden" dot trait function for the SVFG dot graphs to inhibit outputting nodes which no input or output edges. These are uninteresting and just end up compressing the rest of the graph.
3. While studying the pointer analysis in the debugger, I wanted to get a dump of the pointed-to sets, and also, lists of such. I added SVFUtil::dumpSparseSet and SVFUtil::dumpPointsToList. These needed to take a reference as parameter as gdb was not able to construct a copy. To avoid type-mismatch errors for this I added SVFUtil::equalPointsTo and use in MemRegion.h when declaring sets or maps of Points-to sets.
=> Fix DOT graphs, debugging aids

lib/WPA/WPAPass.cpp
Currently a command like
```
wpa -ander -svfg -dump-svfg swap.ll
```
produces an unoptimized SVFG. With this change, a command like this:
```
wpa -ander -svfg --dump-vfg -opt-svfg=false swap.ll
```
will produce an optimized SVFG. Note that the sense of
-opt-svfg seems backward. Should we change this?
This was needed to produced the optimized dot graph of the SVFG
for the wiki.
=> WPAPass: Used -opt-svfg to control creation of optimized SVFG.

include/Util/Options.h, lib/Util/Options.cpp, lib/WPA/WPAPass.cpp
1. Change description of --opt-svfg option to describe what
it really does.
2. Create a new option, ---wpa-opt-svfg, to control whether the
WPAPass uses optimized SVFG. It could have used the same option,
except the old behavior has the opposite default--WPA was
using the unoptimized SVFG but Flow Sensitive was using
optimized by default.
=> Clear confusion regarding --opt-svfg option.

.travis.yml, CMakeLists.txt
Moved tests from travis to cmake. When building the project cmake will check if the Test-suite folder exists. if it does it will build the test bc files and add testing to cmake.
=> Move tests to cmake

.travis.yml, build.sh, include/Graphs/GenericGraph.h, include/Graphs/PAGNode.h, include/Graphs/VFG.h, include/MSSA/MemRegion.h, include/SVF-FE/DCHG.h, include/SVF-FE/GEPTypeBridgeIterator.h, include/Util/BasicTypes.h, include/Util/SVFBasicTypes.h, include/Util/SVFUtil.h, lib/Graphs/ConsG.cpp, lib/Graphs/ExternalPAG.cpp, lib/Graphs/PAG.cpp, lib/Graphs/SVFG.cpp, lib/SABER/LeakChecker.cpp, lib/SVF-FE/CPPUtil.cpp, lib/SVF-FE/DCHG.cpp, lib/SVF-FE/SymbolTableInfo.cpp, lib/Util/ThreadAPI.cpp, lib/Util/TypeBasedHeapCloning.cpp
1. Replace deprecated Callsite/ImmutableCallSite with SVF::CallSite class
2. Fix isNodeHidden() method, which requires two arguments now
3. Fix StringRef to string type conversion
4. Update .travis.yml/build.sh
=> Support LLVM 12.0.0

CMakeLists.txt
Fixes problem introduced in a8c9039:
```
CMake Error at CMakeLists.txt:64 (add_dependencies):
The dependency target "SVF" of target "generatebc" does not exist.
```
To be honest, I have no idea how the CI was able to pass with this error.
=> cmake: Fix incorrect target name in dependency in tests

include/Graphs/SVFG.h, include/Graphs/SVFGNode.h, include/Graphs/VFGNode.h, include/WPA/VersionedFlowSensitive.h, lib/WPA/FlowSensitiveTBHC.cpp, lib/WPA/VersionedFlowSensitive.cpp
This PR introduces two changes:
**BFS instead of DFS for address-taken propagation**
As discussed, propagation is now breadth-first. Since there is no way to add a _propagate o:v to o:v'_ constraint to the solver, I encode this as a dummy node, which holds this information and is pushed into the worklist as required. Otherwise, `propagateVersion` is no longer recursive and some `stmtReliance` stuff is pushed out to `processStore` (previously implied by `propagateVersion`).
**Ignoring existing constraints for call-graph updates**
The changes in `updateConnectedNode` ensure that we don't propagate `o:v` to `o:v'` if it has been done before. `o:v` is not necessarily new to require propagation if a reliance on `o:v` has previously been established.
`vis` is the smallest bitcode I noticed the …
=> Improve VSFS performance

include/MemoryModel/MutablePointsToDS.h, include/Util/SVFUtil.h, lib/WPA/Andersen.cpp
As discussed, this updates reverse points-to sets when calling functions like `clearPts`. It appears to me that changes only need to be done to the base mutable `PTData`, because no other `PTData` handles reverse points-to sets on their own.
I also moved the `insertKey` function to `SVFUtil` (makes more sense to belong there).
I've moved the test for `this->rev` to the caller, not the callee. In theory, this should have a performance impact for long running analyses since the arguments don't need to be processed (though inline, the arguments need to be processed before the test because some have side effects, though I haven't checked the assembly).
In Andersen's, I made the caller to `getRevPts` not take a reference because that looped-over reverse points-to set has iterators invalidated …
=> Account for reverse points-to sets when removing objects

lib/DDA/ContextDDA.cpp
=> contextDDA: fix check on NULL refVal for GEP Objs

include/Graphs/PAG.h
@mbarbar @pietroborrello 
This is a quick solution to make sure that if we creating clashed nodes in the DEBUG strategy, the program will crash.
Please let me know any comments or suggestions.
=> Add assertions when creating a clashed node (guard the DEBUG strategy in NodeIDAllocator)

include/SVF-FE/LLVMUtil.h, lib/SVF-FE/Graph2Json.cpp, lib/SVF-FE/LLVMUtil.cpp
This can cause namespace collisions when trying to include SVF as an external project.
=> Include JSON headers only where required

include/SABER/LeakChecker.h, include/SABER/SrcSnkDDA.h
Hey SVF devs!
Some small mods to the `SrcSnkDDA` class to provide default implementations for some of the virtual methods.
I am trying to extend `SrcSnkDDA` to build my own taint analyzer, and it seems that I have to provide implementations for methods that I don't particularly need. For example, I can implement `initSrcs` and `initSnks` without ever needing to call `isSourceLinkFun` (similarly, `isSinkLikeFun`). Likewise, `isSource` and `isSink` will always just check that the given node is contained within the set of source/sink nodes.
What do you think?
=> SABER: add default implementations for some virtual funcs

include/Graphs/GenericGraph.h
Hi @yuleisui,
I noticed the inverse GraphTraits for `GenericNode` does not dereference edges to their source nodes, but to their destination nodes.
This patch fixes the bug. It also inlines `edge_unary_function()` into the two `GraphTraits` and renames it to `edge_dest()`, as this name is suggested by the `GraphTraits` template.
For completeness, in a separate commit, I also inlined `pair_unary_function()`. This also cleans up the `llvm` namespace a bit.
=> Fix GraphTraits for GenericGraph

include/WPA/VersionedFlowSensitive.h, lib/WPA/VersionedFlowSensitive.cpp
When updating the call graph, if we connect a yielded version `y` to a consumed version `c`, we were propagating `y` to **every** version which relies on `y`, rather than just to `c`. This fixes that. For some benchmarks, this makes a big difference. `lynx` for example, on the first call to update the call graph, adds over 200k edges (!), thus performing redundant propagation.
The `Set` -> `vector` change may also make a difference in extremely large benchmarks.
=> Speed up VSFS

include/Graphs/PAG.h, include/Graphs/SVFG.h, include/Graphs/VFG.h, include/Graphs/VFGNode.h, include/MTA/TCT.h, include/MemoryModel/PersistentPointsToDS.h, include/SVF-FE/PAGBuilder.h, include/SVF-FE/SymbolTableInfo.h, include/Util/NodeIDAllocator.h, include/Util/Options.h, include/Util/SVFBasicTypes.h, include/WPA/VersionedFlowSensitive.h, lib/Graphs/PAG.cpp, lib/Graphs/SVFG.cpp, lib/Graphs/VFG.cpp, lib/SVF-FE/PAGBuilder.cpp, lib/Util/NodeIDAllocator.cpp, lib/Util/Options.cpp, lib/Util/SVFUtil.cpp, lib/WPA/FlowSensitiveStat.cpp
See #485.
I have tested the code with https://gitlab.com/geri0n/svf-test/-/tree/llvmtovfg.
The back map seems not to work with these nodes (since the PAGNodes are not linked to llvm::Values):
- ActualParmSVFGNode
- FormalRetVFGNode
- IntraPHIVFGNode
Moreover an `assert` in the map filling code does not work: `pag->getPAGEdgeNum()` give me way more edges, than I can find in the graph.
=> Add functions for mapping from SVFG nodes to LLVM values and back

CMakeLists.txt, lib/CMakeLists.txt
I have no clue of cmake but this seems to enable building against a globally installed z3 (like per a distribution package).
=> cmake: build correctly with globally installed z3

lib/Graphs/SVFG.cpp
Clang 12 is able to statically determine that `phi` will always be NULL here. This caused build problems on my end, and seems like just a typo.
=> Fix SVFG build error on clang 12

include/MemoryModel/PersistentPointsToDS.h
This PR fixes a compilation error due to missing return in include/MemoryModel/PersistentPointsToDS.h
=> Fix missing return in PersistentDFPTData::getRevPts

include/MemoryModel/PersistentPointsToCache.h, lib/Util/Options.cpp
`ptd`: `mutable` -> `persistent`
`marked-clocks-only`: now true
`node-alloc-strat`: `seq`
For the reserved names, I think we need a bit more discussion, so let's save this till next week.
=> Use better performing defaults.

lib/MemoryModel/PointsTo.cpp
@mbarbar unfortunately the compiler can stripoff assertions and assume that there is no return for a non-void function. 
Any more elegant way to solve this?
=> Suppress warnings if -Werror=return-type is turned on

include/Graphs/SVFGStat.h, include/MemoryModel/PTAStat.h, include/Util/Options.h, lib/SVF-FE/CHG.cpp, lib/Util/Options.cpp, lib/Util/PTAStat.cpp
Basically, `getClk` checks what it wants: it uses `clock` (`CLOCK_IN_MS`) if the option is for CPU time, otherwise it uses `clock_gettime`, returning the value in ms.
I also changed a bunch of calls to the higher level `getClk`.
=> Add option for wall time

lib/MemoryModel/PointsTo.cpp, lib/Util/PTAStat.cpp, lib/Util/SVFUtil.cpp, tools/WPA/CMakeLists.txt
I wasn't able to build the latest commit with gcc 11.1.0 and had to fix some minor issues.
* wpa: pthreads is not linked
* missing return value for non-void functions (fails due to `-Werror`) in three cases
=> Fix build errors (-Werror, wpa: missing pthreads)

include/Util/SVFBasicTypes.h
For some reason there are two identical hashes. I don't have time to fix it now though.
=> first/second vs. p.first/p.second

CMakeLists.txt
We were struggling to use a user-built Z3, this fixes it. .so is not needed as far as I can tell, correct? And when you `make install` by hand the library is in `lib` not `bin`.
=> Be more liberal with Z3 location

lib/Graphs/ICFG.cpp
As discussed, we should not connect callCFGNode to funEntryNode for external API because external API does not contain a function body.
=> do not connect callICFGNode to funcEntry for external API

include/Graphs/ICFGEdge.h, include/MemoryModel/PointsTo.h, include/Util/CoreBitVector.h, lib/MemoryModel/PointsTo.cpp, lib/Util/CoreBitVector.cpp
Removes 3 warnings during compilation: `type qualifiers ignored on function return type`.
=> fix compilation warnings

lib/Util/ExtAPI.cpp
Supporting the [move constructor](https://www.cplusplus.com/reference/string/string/string/) for string.
Tested on something like
```cpp
std::string str("benign");
str = std::string("poison");
sink(str);
```
=> support string move constructor, c++11

include/Util/BasicTypes.h
To Support LLVM 13 in MacOSX 12.4
add dwarf.h in BasicType.h to resolve compile error
=> add include dwarf in BasicType.h

include/Util/ExtAPI.h, lib/Util/ExtAPI.cpp
This PR follows our discussion in PR #736.
Currently, if the default ExtAPI.json path exists, this file will always be read (irrespective if the user wants to use another path).
This patch allows the user to optionally specify a path to an arbitary ExtAPI.json file programatically. If this path is specified, it will be used. Otherwise, the existing lookup process will be used. The user can then call `ExtAPI::getExtAPI("/path/to/my/own/ExtAPI.json")` at the beginning of their program to use it.
Additionally, this patch also fixes a bug in the old `ExtAPI::get_FunJson` function: if the default project path was not found, then the SVF_DIR env variable or NPM is used. However, the jsonFilePath variable was not updated, so the wrong file would be passed to stat to get the file size.
=> Allow arbitrary ExtAPI.json

include/SVF-FE/LLVMModule.h, lib/SVF-FE/LLVMModule.cpp
Sort llvm_global_ctors functions according to their priority. Also support destroy functions. See [LLVM Language Reference Manual](https://llvm.org/docs/LangRef.html#the-llvm-global-ctors-global-variable)
=> llvm.global_ctors/dtors

lib/SVF-FE/SVFIRBuilder.cpp
In the following two cases, SVF fails to determine the correct type of a value used in a memcpy:
1. 
```llvm
%call   = malloc 80
%0      = bitcast i8* %call to %struct.x264_t*
%1      = bitcast %struct.x264_param_t* %param to i8*
call void memcpy(%call, %1, 80)
```
2.
```llvm
%0 = bitcast %struct.x264_param_t* %param to i8*, !dbg !3505
%2 = bitcast %struct.x264_t** %arrayidx to i8**
%3 = load i8*, i8** %2
call void @memcpy(%0, %3, 704)
```
This leads to underapproximations in the pointer analysis.
=> get correct types for values used in memcpy

include/Util/ExtAPI.h, lib/Util/ExtAPI.cpp
In our own analyses, we discover that some user-defined functions implement memory allocation functionality. To make the points-to results more precise in this case, we inform SVF about this.
We used to have a much more invasive patch to SVF for this, but since the introduction of the JSON ExtAPI format, this small patch now suffices.
There's many other ways to go about this change. In fact, SVF already supports this in a way by just parsing & generating a new ExtAPI up front. However, that requires duplicating quite a bit of parsing/JSON format code that SVF already contains anyway. This patch adds a small `add_entry` function to ExtAPI that modifies the in-memory cJSON object directly. 
Let me know if this is not a direction you would like to go with ExtAPI, or if you have any comments. …
=> Make ExtAPI extensible at run time, after parsing

lib/WPA/FlowSensitiveStat.cpp, lib/WPA/TypeAnalysis.cpp, lib/WPA/VersionedFlowSensitiveStat.cpp
As per the discussion in #821, some of the variables here are supposedly not used, causing `-Werror` compilation failures. 
I'm compiling with a recent version of clang, which can probably detect that this variables are initialized, then incremented a few times, but their eventual value is never used. This is basically a more complicated case of a write-only variable, which is also commonly warned on.
We could also remove these counters as a whole, did they used to be logged somewhere perhaps?
=> Add some [[maybe_unused]] annotations to help suppress warnings

lib/MemoryModel/PointerAnalysisImpl.cpp
Changed to use internal flag rather than command line option to decide whether to print stats. This is important to provide control on whether stats get printed when using as library.
=> Fixed print stats error

CMakeLists.txt
In a [recent commit](https://github.com/SVF-tools/SVF/commit/c64457c0bdd57eaba537d44665d8471f9f0ebe52), the ability for shared libz3 objects was (possibly accidentally?) removed from CMakelists.txt. Any problem with re-adding them here?
AFAIK, in the default Ubuntu 20.04 libz3 package, only the shared objects are present.
=> Allow libz3 shared objects again

include/MemoryModel/PointsTo.h, include/MemoryModel/SVFLoop.h, include/SVF-FE/BasicTypes.h, include/SVF-FE/CHGBuilder.h, include/SVF-FE/LLVMLoopAnalysis.h, include/SVF-FE/SymbolTableBuilder.h, include/Util/CoreBitVector.h, include/Util/DPItem.h, include/Util/ExeState.h, include/Util/SparseBitVector.h, include/Util/SymState.h, include/Util/Z3Expr.h
- Adds missing namespace to [include/SVF-FE/BasicTypes.h](https://github.com/SVF-tools/SVF/blob/master/include/Util/BasicTypes.h)
- Removes semicolon from a few namespace parenthesis
- Adds `End namespace SVF` where missing
=> Various fixes regarding the SVF namespace

include/CFL/CFGNormalizer.h, include/CFL/PEGGrammar.txt, lib/CFL/CFGNormalizer.cpp
1. PEGGrammar to shorter EBNF form
2. Correctify * and ? replacement
3. Support '|' replacement
4. Minimize the nonterminal generated during replacement
=> EBNF Form Grammar

lib/Util/ExtAPI.cpp
error message - sh: 1: /path_to_SVF_DIR: Permission denied
cause - popen("$SVF_DIR", "r")
path - jsonFilePath = getJsonFile("$SVF_DIR"); -> GetStdoutFromCommand() -> popen()
=> fix the command of popen()

include/SVF-FE/BasicTypes.h
Without this line, SVF does not compile for me currently.
=> BasicTypes: fix missing include

include/SVF-FE/LLVMUtil.h, lib/SVF-FE/SymbolTableBuilder.cpp
This fixes one typo and replace one deprecated function according to [the LLVM documentation](https://llvm.org/docs/OpaquePointers.html).
BTW, is there any plan how to continue with LLVM 16? As far as I can see, SVF relies heavily on pointer types which will be removed entirely with LLVM 16. We use SVF for [ARA](https://github.com/luhsra/ara) (currently an old version), which in turn also relies on pointer types for other analyses. Migrating to LLVM 16 would make the analyses much more inaccurate. Do you know of any discussion about that topic?
=> LLVM 15 fixes

include/MSSA/MemRegion.h, include/MemoryModel/ConditionalPT.h
Use safer `snprintf` instead to avoid buffer overflows.
=> Fix compiler error under MacOS about unsafe usage of `sprintf`.

.github/workflows/github-action.yml, .gitignore, CMakeLists.txt, build.sh
Those are a couple of smaller fixes that simplify the build system:
* It allows to automatically detect and use systems' LLVM/Z3 libraries if available.
* Support MacOS Z3 dylib
* be more verbose of detected and used libraries
This also allows to use `cmake` directly avoiding the `build.sh` script if not needed, i.e. for alternative configurations.
=> Build system enhancements

lib/CFL/CFLGraphBuilder.cpp
When inserting the inverse label into the `VF` CFL graph, it seems the wrong label is chosen. Here is an example, the original edge added to graph is a `ret`, so the expected inverse edge should be `retbar`, but not `Abar`, as the picture shows. This picture is runtime snapshot.
The reason is that **the wrong kind is chosen**, we should use `edgeLabel`(number 2) rather than `edge->getEdgeKind()`(`VFGEdge::RetDirVF` is number 3) in line 489. Variable `edge` is a `VFGEdge`, the edge kind is not the same as CFL edge kind. The other 3 cases are similar.
=> [Bug] Choosing the right label when creating the inverse edge

include/SVF-LLVM/LLVMModule.h, lib/SVF-LLVM/LLVMModule.cpp
If SVF is used as a library using existing modules, the symbol table would not have been build in the first place.
This fixes the issue.
=> Refactor building symbol method into own function and call it from `buildSVFModule(Module &mod)` as well

include/SVF-LLVM/BasicTypes.h
Add this missing include is required for me when compiling against LLVM 15.0.6
=> Added missing llvm dwarf header include in DCHG.h

svf-llvm/lib/ICFGBuilder.cpp, svf-llvm/lib/SVFIRBuilder.cpp, svf/include/Graphs/ICFGEdge.h, svf/include/SVFIR/SVFStatements.h
When switch-case expression takes i128 type on case destination, getSExtValue raises assertion failure. This patch checks the bit width of ConstantInt and runs getSExtValue only if ConstantInt has a bit width smaller than 64.
Signed-off-by: ChoKyuWon <kyuwoncho18@gmail.com>
=> Fix a assertion failure cause i128 type

svf/lib/SVFIR/SVFIR.cpp
=> fix the condition of SVFIR::isValidPointer

svf-llvm/lib/SVFIRBuilder.cpp, svf-llvm/tools/MTA/LockResultValidator.h, svf/include/SVFIR/SVFModule.h, svf/include/SVFIR/SVFModuleRW.h, svf/include/SVFIR/SVFType.h, svf/include/Util/SVFUtil.h, svf/lib/Util/SVFUtil.cpp
Passing `std::string` requires a clone of a new string everytime, which is inefficient.
We should do with with `const std::string&` instead.
=> Passing `std::string` by const reference instead of by value

svf-llvm/lib/SVFIRBuilder.cpp
Calling getEntryBlock (which calls `front()` of the fun's BBs) for an empty function will cause undefined behaviour.
=> Undefined BB

svf/lib/MemoryModel/PointerAnalysis.cpp
Try to fix some of issues in https://github.com/SVF-tools/SVF/issues/551
=> Connect variadic callees in the call graph

svf-llvm/include/SVF-LLVM/LLVMModule.h, svf-llvm/lib/LLVMModule.cpp, svf-llvm/lib/SymbolTableBuilder.cpp, svf/lib/SVFIR/SVFIRRW.cpp
* Break overly long lines in code
* Rename `build_symbol_table` to `buildSymbolTable` to conform to SVF naming convention
* Replace iterator loop with range-based loop
=> Making coding convention consistent

svf-llvm/lib/LLVMModule.cpp, svf/include/AbstractExecution/BoundedZ3Expr.h, svf/include/AbstractExecution/NumericLiteral.h, svf/include/SVFIR/SVFIRRW.h
* When using expression `m[k]`, map's `operator[]` will construct a value for the key `k` that doesn't exist, so we don't have to handle the code in two ways;
* Removed some unnecessary `static_cast` from `const T*` to `T*`;
* Added some `const` qualifiers to some references and pointers.
=> Refactoring redundant code in `LLVMModule.cpp`

svf/include/WPA/Steensgaard.h, svf/lib/WPA/Steensgaard.cpp
Currently Steensgaard pointer analysis can't update points-to set along indirect calls. This patch is tried to address this gap.
=> Update the callgraph in Steensgaard pointer analysis

svf/lib/Graphs/VFG.cpp
VFG.cpp
in function `getNodeAttributes getSimpleNodeLabel getCompleteNodeLabel`
add `if branch` to deal with BranchVFGNode
BranchVFGNode's color is set to gold just as in SVFG
=> fix VFG dump BranchVFGNode assertion failure bug

svf-llvm/include/SVF-LLVM/LLVMModule.h, svf-llvm/lib/LLVMModule.cpp, svf/include/SVFIR/SVFType.h, svf/include/SVFIR/SymbolTableInfo.h, svf/lib/SVFIR/SymbolTableInfo.cpp
- Transfer the ownership of `StInfo` to `SymbolTableInfo`
- Replace `T<U<...>>` with `T<U<...> >` because astyle cannot handle modern '>>' syntax correctly
- Refactor consecutive calls of `getSVFType(T)` which looks up the same value in the same table multiple times
=> Let `SymbolTableInfo` manages memory deallocation of `StInfo` objects

svf/include/Util/ExtAPI.h, svf/lib/Util/ExtAPI.cpp
Since changing the specification language in the 2.6 release, the `add_entry` functionality of the ExtAPI has been silently broken. This patch fixes it to match the current spec again.
Also added some helper functions to query and set the `overwritten_app_function` field.
=> Update extensible ExtAPI functionality to match new JSON spec

svf/include/Util/ExtAPI.json
See #1078. This starting patch aims to fix `asprintf` and `vasprintf`, others to follow. We inferred the right grammar for these from `posix_memalign`.
=> ExtAPI: update unsoundly modeled functions

CMakeLists.txt
We use SVF as a submodule and build it as part of a larger CMake project. `CMAKE_SOURCE_DIR` evaluates to the source dir where the top level CMake for the current build was invoked (dir of our top-level CMakeLists.txt). Instead, `PROJECT_SOURCE_DIR` evaluates to the top-level dir of the current (sub-)project. When building SVF normally, this makes no difference, but in our case, it does. 
The same goes for the `*_BINARY_DIR` variables: we ideally want SVF's generated `config.h` to be under it's own subdir in our build folder, not globally (to avoid messing with our own generated include paths, for instance). 
After this change, we're able to continue using SVF as a submodule by simply doing:
```
set(SVF_DIR ${CMAKE_CURRENT_SOURCE_DIR}/SVF/)
set(svf_libs SvfLLVM SvfCore) …
```
=> cmake: use paths relative to project source, not cmake top level

.github/workflows/github-action.yml
To find memory usage bugs, turn on small crux bc tests if AddrSanitizer is used.
=> Do small crux bc tests even if ASan is used

.gitignore, svf-llvm/lib/LLVMModule.cpp, svf-llvm/lib/LLVMUtil.cpp, svf/include/SVFIR/SVFType.h, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp, svf/lib/MemoryModel/LocationSet.cpp, svf/lib/SVFIR/SVFFileSystem.cpp, svf/lib/SVFIR/SVFType.cpp, svf/lib/SVFIR/SymbolTableInfo.cpp
To make string representation of SVF data structure independent of LLVM BC, we need to remove both
- `SVFType::toString()`
- `SVFValue::toString()`
and store necessary information in SVF IR.
This is the part 1 of it.
=> Make printing `SVFType` independent of LLVM BC

svf-llvm/lib/LLVMModule.cpp
```sh
typedef struct Data
{
float a;
int b;
char c;
char cc[3];
short d;
void *ptr;
} Data;
Data arr[2][5];
```
```sh
{SVFArrayType: [2 x [5 x %struct.Data]]}
fldIdxVec
0
0
elemIdxVec
0
30
fldIdx2TypeMap
0 ==> SVFStructTy %struct.Data = type { float, i32, i8, [3 x i8], i16, i8* }
finfo
SVFOtherTy float
SVFIntegerTy i32
SVFIntegerTy i8
SVFIntegerTy i8
SVFIntegerTy i16
SVFPointerTy i8*
stride
10
numOfFlattenElements
60
numOfFlattenFields
6
{SVFStructType: %struct.Data = type { float, i32, i8, [3 x i8], i16, i8* }}
fldIdxVec
0
1
2
3
4
5
elemIdxVec
0
1
2
3
6
7
fldIdx2TypeMap
5 ==> SVFPointerTy i8*
4 ==> SVFIntegerTy i16
3 ==> SVFArrayTy [3 x i8]
2 ==> SVFIntegerTy i8
1 ==> SVFIntegerTy i32
0 ==> SVFOtherTy float
finfo
SVFOtherTy float
SVFIntegerTy i32
SVFIntegerTy i8
SVFIntegerTy i8 …
```
=> Update collectArrayInfo() and collectStructInfo()

svf/include/SABER/SrcSnkDDA.h, svf/include/Util/SVFBugReport.h, svf/lib/Util/SVFBugReport.cpp
This PR enables various checkers (leak checker, free checker, etc) to have access to bug reports after running on modules. 
It also adds literal strings for `GenericBug::BugType`.
Please refer to issue #1104 . Close #1104 after PR.
=> add getSVFBugReport for SrcSnkDDA

svf-llvm/include/SVF-LLVM/LLVMUtil.h, svf-llvm/lib/CHGBuilder.cpp, svf-llvm/lib/DCHG.cpp, svf-llvm/lib/LLVMUtil.cpp
=> fix: support programs built w/ ASan (#1114)

svf-llvm/include/SVF-LLVM/SVFIRBuilder.h, svf-llvm/lib/SVFIRBuilder.cpp, svf-llvm/lib/SVFIRExtAPI.cpp, svf-llvm/tools/MTA/LockResultValidator.cpp, svf/include/Graphs/ConsG.h, svf/include/Graphs/ConsGEdge.h, svf/include/MemoryModel/AccessPath.h, svf/include/MemoryModel/PointerAnalysis.h, svf/include/SVFIR/SVFFileSystem.h, svf/include/SVFIR/SVFIR.h, svf/include/SVFIR/SVFStatements.h, svf/include/SVFIR/SVFVariables.h, svf/include/SVFIR/SymbolTableInfo.h, svf/lib/Graphs/ConsG.cpp, svf/lib/MemoryModel/AccessPath.cpp, svf/lib/MemoryModel/PointerAnalysisImpl.cpp, svf/lib/SVFIR/SVFFileSystem.cpp, svf/lib/SVFIR/SVFIR.cpp, svf/lib/SVFIR/SVFVariables.cpp, svf/lib/SVFIR/SymbolTableInfo.cpp, svf/lib/WPA/Andersen.cpp
Rename variables with name legacy name `ls`(locationSet) to `ap`(accessPath) or `apOffset`(access path offset) to make naming consistent with type
=> Making naming consistent with type

svf-llvm/lib/LLVMUtil.cpp, svf-llvm/lib/SymbolTableBuilder.cpp
Avoid repetitive checks like
```
bool b = false; 
if (X) b = true; 
if (Y) b = true;
...
return b;
```
Return immediately when any condition is satisfied.
=> Avoid repetitive checks in `LLVMUtil::isObject()`

svf/include/Util/ExtAPI.json
The non-throwing versions of `new` behave similarly to the throwing versions, I believe.
=> Support non-throwing C++ `new` functions in ExtAPI

svf/lib/MemoryModel/AccessPath.cpp
for negative offset, we do not need to get FlattenIdx.
=> fix a bug in computeConstantOffset

svf/include/WPA/AndersenPWC.h
fix a nullptr dereference when creating AndersenSCD singleton instance
=> fix a nullptr dereference error

svf-llvm/include/SVF-LLVM/LLVMUtil.h, svf/include/AbstractExecution/SVFIR2ItvExeState.h, svf/include/MemoryModel/AccessPath.h, svf/include/SVFIR/SVFStatements.h, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp, svf/lib/MemoryModel/AccessPath.cpp
- add SVFType2ByteSize in LLVMUtil
- add u32 elem_bytesize and bool getByteOffset to support byte size
=> fix getgepoffset and accumulateconstantOffset

svf-llvm/include/SVF-LLVM/BasicTypes.h, svf-llvm/include/SVF-LLVM/LLVMUtil.h, svf-llvm/lib/LLVMUtil.cpp, svf-llvm/lib/SVFIRBuilder.cpp
When I use SVF to do some research on static (sparse) symbolic execution, e.g., translate SVFG/VFGNode to Z3 Formula. I think the the following code will lead to some incorrect formulas.
Given the code:
```c
#include <stdio.h>
void test(int a) {
switch (a)
{
case 0: printf("0\n"); break;
case 1:
case 2:
case 3: printf("a >=1 && a <= 3\n"); break;
case 4:
case 6:
case 7:  printf("a >= 4 && a <=7\n"); break;
default: printf("a < 0 || a > 7"); break;
}
}
```
SVF will get many incorrect target case value -1 `due to use of API SwitchInst::findCaseDest`. Here is comments about SwitchInst::findCaseDest:
```c
/// Finds the unique case value for a given successor. Returns null if the
/// successor is not found, not unique, or is the default case.
ConstantInt *findCaseDest(BasicBlock *BB) {
// ... …
```
=> fix a bug that leads to get many incorrect switch target case value -1

svf/include/AbstractExecution/ConsExeState.h, svf/include/AbstractExecution/IntervalExeState.h, svf/include/Graphs/ICFGWrapper.h, svf/include/SVFIR/SVFType.h
- add include cstdint
- add using Base::Func to avoid compiler err in GCC 13.2
=> fix compiler err in gcc13.2

svf/include/Graphs/CFBasicBlockG.h
CFBasicBlockEdge can have an empty icfg edge (newly added edge). We add a null check to prevent potential null dereference.
=> fix potential null dereference

build.sh, svf-llvm/CMakeLists.txt, svf/CMakeLists.txt, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp
In previous versions, we specified "STATIC" when using `add_library`, which enforced the result to be a static library. This pull request eliminates this constraint.
=> Allow building of shared libraries

CMakeLists.txt, svf-llvm/CMakeLists.txt
- LLVM_DIR is overridden as LLVM_DIR/lib/cmake due to the configuration in LLVMConfig.cmake. We should reset LLVM_DIR as the root directory of LLVM if we want to use LLVM_DIR as before.
- Use LLVM_DIR as a hint to find the path of Clang. This can ensure that the clang version used to build extapi.bc is consistent with the llvm library used in SVF.
=> fix LLVM_DIR rewrite by LLVMConfig.cmake

svf-llvm/lib/LLVMUtil.cpp, svf-llvm/tools/Example/svf-ex.cpp, svf/include/AbstractExecution/SVFIR2ItvExeState.h, svf/include/MemoryModel/AccessPath.h, svf/include/SVFIR/SVFStatements.h, svf/include/SVFIR/SVFType.h, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp, svf/lib/MemoryModel/AccessPath.cpp, svf/lib/SVFIR/SVFType.cpp
- add getLLVMByteSize in SVFType
- fix getByteOffset in SVFIR2ExeState and GepStmt
=> fix getByteOffsets in GepStmt and SVFIR2ItvExeState

svf/lib/MemoryModel/AccessPath.cpp
since it is from External API like memcpy
```
"GepStmt: [Var96744 <-- Var4683]\t\n   call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 %13, i8* align 1 %15, i64 8, i1 false), !dbg !26775 { \"ln\": 162, \"cl\": 2, \"fl\": \"/devcloud/ws/sQEab/workspace/j_gIcjhi8u/code/tests/allocator.cpp\" }"
```
this GepStmt comes from memcpy, which offsetVarAndGepTypePair[i].second  is always nullptr
=> fix if offsetVarAndGepTypePair.second is nullptr 

svf-llvm/include/SVF-LLVM/LLVMModule.h, svf-llvm/lib/LLVMModule.cpp
Use `static SVFModule* buildSVFModule(Module& mod, std::unique_ptr<LLVMContext> context)` to create an svfModule. It is necessary to ensure that the LLVM Context of the `mod` and the `extapi module`'s LLVM Context are the same, meaning the `context` parameter should be the `mod`'s LLVM Context.
=> Load extapi module in buildSVFModule(Module& mod)

svf-llvm/include/SVF-LLVM/SymbolTableBuilder.h, svf-llvm/lib/SymbolTableBuilder.cpp, svf-llvm/lib/extapi.c, svf/include/SVFIR/SymbolTableInfo.h, svf/lib/SVFIR/SymbolTableInfo.cpp
1) add getByteSizeofObj() and isConstantByteSize() in SymbolTableInfo.h/cpp
2) add annotation to ALLOC_RET and ALLOC_ARGi extapis in extapi.c
3) add analyzeHeapAllocByteSize() in SymbolTableBuilder.h/cpp to handle ALLOC_RET and ALLOC_ARGi
=> 1st PR of more precise ObjTypeInfo

svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp
strong update for translating phi
=> strong update for translating phi

svf-llvm/include/SVF-LLVM/LLVMUtil.h, svf-llvm/lib/LLVMModule.cpp, svf-llvm/lib/LLVMUtil.cpp, svf/include/SVFIR/SVFValue.h, svf/lib/Graphs/ICFG.cpp, svf/lib/SVFIR/SVFValue.cpp
reproduce the bug:
given the code in file bb.c:
```c
int print();
void test()
{
for (int i = 0 ; i < 100 ; i++)
{
print();
}
}
```
compile and optimize the code with the following commands:
```shell
clang -S -c -Xclang -disable-O0-optnone -fno-discard-value-names -emit-llvm -o bb.ll bb.c
opt -loop-unroll -unroll-count=3 -S -o bb.ll.ll bb.ll
```
we get the final optimized bitcode file `bb.ll.ll` and get the code of test function:
```c
; Function Attrs: noinline nounwind ssp uwtable
define void @test() #0 {
entry:
%i = alloca i32, align 4
store i32 0, i32* %i, align 4
br label %for.cond
for.cond:                                         ; preds = %for.inc.2, %entry
%0 = load i32, i32* %i, align 4
%cmp = icmp slt i32 %0, 100
br i1 %cmp, label %for.body, label %for.end
for.body: …
```
=> fix a bug: 'getExitBB' of SVFFunction may get incorrect exit block.

svf/include/AbstractExecution/ConsExeState.h, svf/include/AbstractExecution/ExeState.h, svf/include/AbstractExecution/IntervalExeState.h, svf/include/AbstractExecution/SVFIR2ConsExeState.h, svf/include/AbstractExecution/SVFIR2ItvExeState.h, svf/lib/AbstractExecution/ConsExeState.cpp, svf/lib/AbstractExecution/ExeState.cpp, svf/lib/AbstractExecution/IntervalExeState.cpp, svf/lib/AbstractExecution/SVFIR2ConsExeState.cpp, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp
=> rename API names in AE

svf-llvm/lib/SVFIRBuilder.cpp, svf-llvm/lib/SVFIRExtAPI.cpp, svf/include/Graphs/ConsGEdge.h, svf/include/MemoryModel/AccessPath.h, svf/include/SVFIR/SVFStatements.h, svf/include/SVFIR/SVFVariables.h, svf/lib/AbstractExecution/SVFIR2ConsExeState.cpp, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp, svf/lib/DDA/ContextDDA.cpp, svf/lib/DDA/FlowDDA.cpp, svf/lib/MemoryModel/AccessPath.cpp, svf/lib/SVFIR/SVFIR.cpp, svf/lib/WPA/Andersen.cpp, svf/lib/WPA/FlowSensitive.cpp
Xiao will add getSrcType and modify  AccessPath::computeConstantOffset().
=> rename getConstantFldIdx to getConstantStructFldIdx

svf-llvm/lib/SVFIRBuilder.cpp, svf/include/MemoryModel/AccessPath.h, svf/lib/MemoryModel/AccessPath.cpp
This patch adds a field sourceElementType in accesspath, e.g.,
```cpp
%f1 = getelementptr inbounds %struct.MyStruct, %struct.MyStruct* %arrayidx, i32 0, i32 0
```
The source element type is %struct.MyStruct
This is also useful for the migration regarding opaque pointers (https://llvm.org/docs/OpaquePointers.html#migration-instructions).
=> add source element type in accesspath

svf/include/MemoryModel/AccessPath.h, svf/lib/MemoryModel/AccessPath.cpp
rename sourceElementType, fix computeConstantOffset bug
=> rename sourceElementType, fix computeConstantOffset bug

svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp, svf/lib/MemoryModel/AccessPath.cpp
if offset is larger than so.size(), set offset the last element.
=> fix offset>=so.size() assertion

svf-llvm/lib/LLVMModule.cpp, svf/include/SVFIR/SVFValue.h, svf/lib/Graphs/ICFG.cpp, svf/lib/SVFIR/SVFValue.cpp, svf/lib/Util/CFBasicBlockGBuilder.cpp
do not connect return BB edge for no return function that does not have an exit BB
=> fix CFBBGbuilder bug

svf-llvm/lib/LLVMModule.cpp
As name from app and extapi modules can only have exactly one match, we can break after find it.
The benefit is not limited to performance. 
Take a look at the loop of the second break: `fun` is casted out of `appfunc` from `funDefs`, which is the function list of app module.
Then, `fun->eraseFromParent()` remove that function from the function list. This is ultimately a `list->remove()` operation, see: https://github.com/llvm/llvm-project/blob/main/llvm/lib/IR/Function.cpp#L389
This operation will release the object of `fun`, and also `appfunc`, so when we still try to compare `appfunc` with `owfunc`, the behavior is undefined.
I received a SIGSEGV at line 960 (original version) after thousands of calls to `appfunc->getName()` after the first match. Both the bc file and extapi are quite …
=> Break when app and extapi module have a match

svf/lib/Graphs/SVFG.cpp, svf/lib/Graphs/VFG.cpp
connect actual to formal vfgnode for full svfg
=> (fix issue #1279) connect actual to formal vfgnode for full svfg

svf-llvm/include/SVF-LLVM/LLVMUtil.h, svf-llvm/lib/LLVMUtil.cpp, svf-llvm/lib/SVFIRBuilder.cpp, svf-llvm/lib/SymbolTableBuilder.cpp
Solve problem described in #1289.
Sometimes a return value of heap allocation has multiple uses. We need to find out the one right next to it, and make sure it is a `bitcast` operation. This requires performing a scan over all uses and find out the last one, which corresponds to the first use in human readable IR.
=> consider multiple uses of heap object

svf-llvm/include/SVF-LLVM/LLVMModule.h, svf-llvm/lib/LLVMModule.cpp
The recent commit merged in #1258 modified the interface to build an `SVF::SVFModule` instance from an `llvm::Module` object to include a `std::unique_ptr<llvm::LLVMContext>` parameter to specify the context used when loading the `ExtAPI` module. This change introduces a number of issues however, particularly when using SVF from an LLVM pass.
Most critically, the use of `std::unique_ptr<>` creates problems when SVF is used from an LLVM pass, as automatic garbage collection on the context is done incorrectly. Creating a unique pointer based on the context of the LLVM module incorrectly means ownership of the context is taken by the `LLVMModuleSet` object. This causes issues because the context is obviously not uniquely owned by the module set; when an SVFModule is built from an LLVM …
=> Get LLVMContext instance directly from `llvm::Module` when building SVFModule

svf-llvm/include/SVF-LLVM/BasicTypes.h, svf-llvm/include/SVF-LLVM/LLVMUtil.h, svf-llvm/lib/LLVMModule.cpp, svf-llvm/lib/LLVMUtil.cpp, svf-llvm/lib/SVFIRBuilder.cpp, svf-llvm/lib/SymbolTableBuilder.cpp, svf/include/MemoryModel/AccessPath.h, svf/lib/AbstractExecution/SVFIR2ConsExeState.cpp, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp, svf/lib/MemoryModel/AccessPath.cpp, svf/lib/MemoryModel/PointerAnalysis.cpp, svf/lib/SVFIR/SVFType.cpp, svf/lib/SVFIR/SymbolTableInfo.cpp
remove some opaque pointer dependencies
=> remove some opaque pointer dependencies

svf/lib/Util/ExtAPI.cpp
=> bugfix: check return value of getenv

svf-llvm/lib/SVFIRBuilder.cpp, svf/lib/MemoryModel/AccessPath.cpp
1. assert that we can have at most one pointer type (normally the first index that simply pieces the base pointer) when bridging a gep instruction. 
2. remove the assertion checking in getelementNum because the pointee may be of a pointer type for the multi-level pointer, e.g., `%2 = getelementptr inbounds i32*, i32** %1, ... ` the corresponding source code is like:
```cpp
int getValue(int** arr, int x, int y) {
return arr[x][y];
}
```
This can be transformed to:  `%2 = getelementptr inbounds [N x i32], [N x i32]* %1, ...`
However, we do not know `N` without context information. `int**` implies **non-contiguous blocks of memory**. In this case, we conservatively return the max field limit.
=> make the pointee type related to gep more robust

svf/include/CFL/CFLSVFGBuilder.h, svf/include/Graphs/SVFG.h, svf/include/SABER/ProgSlice.h, svf/include/SABER/SaberCondAllocator.h, svf/include/SABER/SaberSVFGBuilder.h, svf/lib/CFL/CFLSVFGBuilder.cpp, svf/lib/SABER/ProgSlice.cpp, svf/lib/SABER/SaberSVFGBuilder.cpp, svf/lib/SABER/SrcSnkDDA.cpp
fix issue #1306: we compute the vf guard of invalid branches stemming from removed strong-update value-flow, and conjunct the negation of that.
=> fix issue #1306: compute vf guard for strong update in another branch

svf/include/Util/SVFStat.h, svf/lib/AbstractExecution/SVFIR2ItvExeState.cpp
1. in SVFStat.h. 
```
typedef OrderedMap<std::string, u32_t> NUMStatMap;
```
The key type should be string, since `const char*` cannot support NUMStatMap["$KEYNAME"]
2. in SVFIR2ItvExeState.cpp
add SVFOtherType handler, since float/double is one of SVFOtherType, the intervalValue range of double/float is s32_t's range.
=> Fix bugs for big program

svf-llvm/include/SVF-LLVM/SVFIRBuilder.h, svf-llvm/lib/SVFIRBuilder.cpp, svf-llvm/lib/SVFIRExtAPI.cpp, svf/include/SVFIR/SVFStatements.h
1) add addAddrWithAllocArraySz, the arg is AllocaInst and CallBase 
2) add arraySize getter/setter to AddrStmt
=> add arraySize to AddrStmt

svf/include/DDA/DDAStat.h, svf/include/Graphs/ConsG.h, svf/include/Util/PTAStat.h, svf/lib/DDA/DDAStat.cpp, svf/lib/Graphs/ConsG.cpp, svf/lib/Util/PTAStat.cpp, svf/lib/WPA/Andersen.cpp, svf/lib/WPA/AndersenStat.cpp
As shown in the above graph, in this patch,
1) memory statistics of WPA are now printed;
2) non-pointer nodes which are not connected by any edge are removed from constraint graph in the preprocessing stage, which reduced time and memory consumption.
=> Add Memory Statistics and Clean Solitaries in Constraint Graph

svf-llvm/include/SVF-LLVM/ObjTypeInference.h, svf-llvm/lib/ObjTypeInference.cpp
Selecting from an unordered container is non-deterministic. This may lead to different node id allocation in different executions.
=> use orderedset to select largest type

svf-llvm/CMakeLists.txt
Ensure extapi.bc built before libSvfLLVM such that we don't have to build all when building individual tools (e.g., wpa).
=> build extapi.bc before svfllvm

svf-llvm/lib/CppUtil.cpp
This pull request fixes a bug that caused call graphs to be incomplete/incorrect when using C++ namespaces and virtual functions.
Currently, whenever namespaces and virtual functions are used with C++ classes, the underlying object's name is used to find the VTable for a called function. However, the name used therein is incorrect (the namespace component is stripped off when it shouldn't be), and causes incomplete and incorrect results to be returned, leading to an incomplete callgraph.
For example, take the following snippets:
Example 1:
```
#include <cstdio>
#include <cstring>
class Parent
{
public:
Parent( )          = default;
virtual ~Parent( ) = default;
virtual void action( ) = 0;
};
class Child : public Parent
{
public:
Child( )  = default;
~Child( ) = default;
void action( ) { …
```
=> Fix incomplete/incorrect PTA when using C++ namespaces & virtual functions

svf-llvm/include/SVF-LLVM/ObjTypeInference.h, svf-llvm/lib/CppUtil.cpp, svf-llvm/lib/ObjTypeInference.cpp
After the pull request I submitted yesterday (#1369) was merged I noticed another issue with C++ virtual functions and the way SVF retrieves the class name (used to determine which function is called for overloaded/virtual functions in derived classes) leading to an incomplete/incorrect call graph being generated.
This fix possibly also addresses issues #1314 and #1301.
This issue is caused by an incorrect way of retrieving the class name when the Class Hierarchy Graph is being built, which relies on the LLVM type and the assumption that an LLVM type can be relied upon for retrieving a class' name. However, if two classes have identical types (but can still have e.g. different overloaded function definitions) LLVM can choose to merge those types. Depending on the order of definition, LLVM …
=> Fix incomplete/incorrect callgraphs due to incorrect class names

setup.sh
$Z3_BIN is not defined in the setup.sh script, and libz3.so is located in the $Z3_DIR/bin directory.
=> fix LD_LIBRARY_PATH error in setup.sh

svf-llvm/include/SVF-LLVM/BasicTypes.h, svf-llvm/lib/LLVMUtil.cpp
There were only very few changes from llvm 16 to llvm 17
-  Module::getGlobalList() was made private since insertGlobalVariable() was added 
- DbgInfoIntrinsic was used instead of DbgAddrIntrinsic, as debug.addr was removed from the IR
fixing these issues lets SVF build with llvm 17 and passes all the tests in the test suite.
=> Add llvm-17.0.6 support

.gitattributes
By setting this, we ensure that all text files checked out will have LF line endings on every system, and when committed, regardless of the local development environment's line ending configurations.
=> add LF check

svf/include/Util/SparseBitVector.h
Make it have a behavior symmetric to `countLeadingZeros` (just like the code in LLVM).
=> Try to call compiler built-in functions in `countTrailingZeros`

svf/include/Graphs/CDG.h, svf/lib/Graphs/CDG.cpp, svf/lib/Util/CDGBuilder.cpp
=> fix cdg null deref

setup.sh
```bash
if set_llvm; then
export LLVM_DIR
export PATH="$LLVM_DIR/bin:$PATH" # redundant
echo "LLVM_DIR=$LLVM_DIR"
else
echo "- LLVM_DIR not set, probably system-wide installation"
fi
...
if set_z3; then
export Z3_DIR
echo "Z3_DIR=$Z3_DIR"
else
echo "- Z3_DIR not set, probably system-wide installation"
fi
...
export PATH=$LLVM_DIR/bin:$Z3_DIR/bin:$PATH
```
The annotated statement (`export PATH="$LLVM_DIR/bin:$PATH"`) is redundant, because there exists another statement (`export PATH=$LLVM_DIR/bin:$Z3_DIR/bin:$PATH`) below.
=> remove a redundant statement in setup.sh

svf/lib/SABER/SaberCondAllocator.cpp
=> remove casting to intraicfgnode when allocating branch condition

svf-llvm/include/SVF-LLVM/ICFGBuilder.h, svf-llvm/include/SVF-LLVM/LLVMModule.h, svf-llvm/lib/ICFGBuilder.cpp, svf-llvm/lib/LLVMLoopAnalysis.cpp, svf-llvm/lib/LLVMModule.cpp, svf-llvm/lib/LLVMUtil.cpp
=> add process unreachable bbs

svf/include/Graphs/SCC.h, svf/include/WPA/WPAFSSolver.h, svf/lib/MSSA/MemRegion.cpp, svf/lib/WPA/Andersen.cpp
an example of test.c:
```c
#include <stdlib.h>
#define SZ 100
int* mem_alloc(unsigned sz)
{
int *buf = (int *)malloc(sizeof(int) * sz);
return buf;
}
void set_mem(int *ar, int x)
{
ar[0] = x;
ar[x] = 0;
}
void baz(int arg)
{
int *buf = mem_alloc(SZ);
set_mem(buf, 1);
int t1 = buf[0];
int t2 = buf[1];
buf[t1-1] = 0;
buf[t2-1] = 0;
}
```
before fix, `MRGenerator::getCallGraphSCCRevTopoOrder` will get:
```
baz
set_mem
mem_alloc
malloc
```
after fix, it will get:
```
malloc
mem_alloc
set_mem
baz
```
=> fix incorrect implementation of getting CallGraphSCCRevTopoOrder

svf-llvm/include/SVF-LLVM/ObjTypeInference.h, svf-llvm/lib/ObjTypeInference.cpp, svf-llvm/lib/SVFIRBuilder.cpp
fix issue #1650 
--- log/nginx.log	2025-02-11 10:27:54.119860076 +1100
+++ log/nginx-xiao.log	2025-02-11 10:28:55.531230995 +1100
@@ -39,9 +39,9 @@
VarArrayObj         153
VarStructObj        630
----------------Time and memory stats--------------------
-LLVMIRTime          1.236
-SVFIRTime           1.473
-SymbolTableTime     0.17
+LLVMIRTime          1.208
+SVFIRTime           1.429
+SymbolTableTime     0.169
#######################################################
*********PTACallGraph Stats (Andersen analysis)***************
@@ -68,11 +68,11 @@
CollapseTime        0
CopyGepTime         0
LoadStoreTime       0
-MemoryUsageVmrss    2.3221e+06
+MemoryUsageVmrss    2.32208e+06
MemoryUsageVmsize   2.3222e+06
SCCDetectTime       0
SCCMergeTime        0
-TotalTime           126.089
+TotalTime …
=> fix getbasevalueforextarg

.github/workflows/docker_publish.yml, .github/workflows/svf-lib_publish.yml, Dockerfile, build.sh
1. Make Arm docker and X86 Docker use same Python 3.10
2. Github CI docker publish Arm docker
3. Fix build.sh to support LLVM ARM RTTI
4. Fix SVF Lib Publish, to support SVF-linux-x86 and SVF-linux-arm. (Should also change the Repo SVF-npm)
=> Fix Arm64 toolkit

svf/include/Graphs/CallGraph.h, svf/lib/Graphs/CallGraph.cpp
I faced an issue when wpa spends most of the time in `verifyCallGraph`, but this function doesn't do anything useful without `-dwarn=false`.
Without patch:
```
62,56%  wpa      libSvfCore.so         [.] SVF::CallGraphNode::isReachableFromProgEntry() const                                                                                                                                       
16,23%  wpa      libstdc++.so.6.0.33   [.] std::_Rb_tree_increment(std::_Rb_tree_node_base const*)                                                                                                                                    
5,79%  wpa      libSvfCore.so         [.] std::_Rb_tree_increment(std::_Rb_tree_node_base const*)@plt …
```
=> Speedup verifier

.cmake-format.py, .github/workflows/github-action.yml, svf-llvm/include/SVF-LLVM/LLVMModule.h, svf-llvm/lib/extapi.c, svf/include/Graphs/SVFGOPT.h, svf/include/Graphs/VFG.h, svf/include/MSSA/SVFGBuilder.h, svf/include/WPA/VersionedFlowSensitive.h, svf/lib/Graphs/SVFGOPT.cpp, svf/lib/MSSA/SVFGBuilder.cpp
As per @yuleisui's request in [this pull request (1697)](https://github.com/SVF-tools/SVF/pull/1697), this pull request contains the various fixes, improvements, and other changes unrelated to the build system. Note that this pull request contains one additional commit [c1306f4] not in the original pull request [1697], which adds some additional allocator definitions to `extapi.c` and ensures existing ones are consistent.
This PR consolidates six orthogonal areas of work into one release:
- **CI/Workflow**: harden coverage removal flags in GitHub Actions  
- **CMake Formatting**: add `cmake-format` config for consistent styling & formatting  
- **API Additions**: add missing `has…()` checks alongside existing getters  
- **WPA Backends**: unify public interface for polymorphic use  
- …
=> CI, Formatting, API & SVFG Builder Improvements

CMakeLists.txt
After my previous pull request #1703 was merged, commit a745cdc changed the default installation prefix for public headers from `include/SVF` to just `include`. As discussed in [my last comment](https://github.com/SVF-tools/SVF/issues/1703#issuecomment-2901506766_) on pull request #1703, installing into a dedicated project prefix can often be desirable for clarity and maintenance. To make this behaviour optional, I included user-configurable build parameters like `SVF_INSTALL_INCLUDEDIR` and `SVF_INSTALL_BINDIR` to override the default installation prefixes.
However, I made a mistake in defining the type of these parameters; they are currently defined as `PATH` types instead of `STRING` types. As these defaulted to their `${CMAKE_INSTALL_<...>}` counterparts (which are always correctly …
=> Changed types of SVF install prefix configuration parameters to STRING to avoid absolute path prefixes

svf/lib/Util/ExtAPI.cpp
Priority:
- 1. If setExtBcPath() has been called, use that path.
- 2. If the command line argument -extapi=path/to/extapi.bc is provided, use that path.
- 3. If SVF is being developed and used directly from a build directory, try the build dir (SVF_BUILD_DIR).
- 4. If the SVF_DIR environment variable is set, try $SVF_DIR with the standard relative path.
- 5. If installed via npm, use `npm root` and append the standard relative path.
- 6. As a last resort, use the directory of the loaded libSVFCore.so (or .dylib) and append extapi.bc.
=> fix ExtAPI

svf/include/AE/Core/AddressValue.h
We don't need to detect wthether the addr is null in 'isVirtualMemAddress'. we will detect it later. and we can not detect it here since if we detect it here
inline void store(u32_t addr, const AbstractValue &val)
{
assert(isVirtualMemAddress(addr) && "not virtual address?");
u32_t objId = getIDFromAddr(addr);
if (isNullMem(addr)) return;
_addrToAbsVal[objId] = val;
}
in store function. the isVirtualMemAddress will be false if the addr is null, so the program would abort. That's not what we want, and we detect isNullMem in store function, so the function is safe.
and we will detect null dereference in store statement, so we can detect it .
=> fix logical error
